// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.brilltech.jelp.entities;

public final class AccountProto {
  private AccountProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AddUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.AddUserRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .brilltech.jelp.entities.User user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>optional .brilltech.jelp.entities.User user = 1;</code>
     */
    UserProto.User getUser();

    /**
     * <code>optional string password = 3;</code>
     */
    String getPassword();
    /**
     * <code>optional string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
     */
    int getDeviceTypeValue();
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
     */
    JelpProto.DeviceType getDeviceType();

    /**
     * <code>optional string deviceInfo = 5;</code>
     */
    String getDeviceInfo();
    /**
     * <code>optional string deviceInfo = 5;</code>
     */
    com.google.protobuf.ByteString
        getDeviceInfoBytes();

    /**
     * <code>optional string deviceId = 6;</code>
     */
    String getDeviceId();
    /**
     * <code>optional string deviceId = 6;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>optional string pushToken = 7;</code>
     */
    String getPushToken();
    /**
     * <code>optional string pushToken = 7;</code>
     */
    com.google.protobuf.ByteString
        getPushTokenBytes();

    /**
     * <code>optional string ip = 8;</code>
     */
    String getIp();
    /**
     * <code>optional string ip = 8;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.AddUserRequest}
   */
  public  static final class AddUserRequest extends
      com.google.protobuf.GeneratedMessageLite<
          AddUserRequest, AddUserRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.AddUserRequest)
      AddUserRequestOrBuilder {
    private AddUserRequest() {
      password_ = "";
      deviceInfo_ = "";
      deviceId_ = "";
      pushToken_ = "";
      ip_ = "";
    }
    public static final int USER_FIELD_NUMBER = 1;
    private UserProto.User user_;
    /**
     * <code>optional .brilltech.jelp.entities.User user = 1;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>optional .brilltech.jelp.entities.User user = 1;</code>
     */
    public UserProto.User getUser() {
      return user_ == null ? UserProto.User.getDefaultInstance() : user_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.User user = 1;</code>
     */
    private void setUser(UserProto.User value) {
      if (value == null) {
        throw new NullPointerException();
      }
      user_ = value;
      
      }
    /**
     * <code>optional .brilltech.jelp.entities.User user = 1;</code>
     */
    private void setUser(
        UserProto.User.Builder builderForValue) {
      user_ = builderForValue.build();
      
    }
    /**
     * <code>optional .brilltech.jelp.entities.User user = 1;</code>
     */
    private void mergeUser(UserProto.User value) {
      if (user_ != null &&
          user_ != UserProto.User.getDefaultInstance()) {
        user_ =
          UserProto.User.newBuilder(user_).mergeFrom(value).buildPartial();
      } else {
        user_ = value;
      }
      
    }
    /**
     * <code>optional .brilltech.jelp.entities.User user = 1;</code>
     */
    private void clearUser() {  user_ = null;
      
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private String password_;
    /**
     * <code>optional string password = 3;</code>
     */
    public String getPassword() {
      return password_;
    }
    /**
     * <code>optional string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>optional string password = 3;</code>
     */
    private void setPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
    }
    /**
     * <code>optional string password = 3;</code>
     */
    private void clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>optional string password = 3;</code>
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value.toStringUtf8();
    }

    public static final int DEVICETYPE_FIELD_NUMBER = 4;
    private int deviceType_;
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
     */
    public int getDeviceTypeValue() {
      return deviceType_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
     */
    public JelpProto.DeviceType getDeviceType() {
      JelpProto.DeviceType result = JelpProto.DeviceType.forNumber(deviceType_);
      return result == null ? JelpProto.DeviceType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
     */
    private void setDeviceTypeValue(int value) {
        deviceType_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
     */
    private void setDeviceType(JelpProto.DeviceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      deviceType_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
     */
    private void clearDeviceType() {
      
      deviceType_ = 0;
    }

    public static final int DEVICEINFO_FIELD_NUMBER = 5;
    private String deviceInfo_;
    /**
     * <code>optional string deviceInfo = 5;</code>
     */
    public String getDeviceInfo() {
      return deviceInfo_;
    }
    /**
     * <code>optional string deviceInfo = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceInfoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceInfo_);
    }
    /**
     * <code>optional string deviceInfo = 5;</code>
     */
    private void setDeviceInfo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceInfo_ = value;
    }
    /**
     * <code>optional string deviceInfo = 5;</code>
     */
    private void clearDeviceInfo() {
      
      deviceInfo_ = getDefaultInstance().getDeviceInfo();
    }
    /**
     * <code>optional string deviceInfo = 5;</code>
     */
    private void setDeviceInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceInfo_ = value.toStringUtf8();
    }

    public static final int DEVICEID_FIELD_NUMBER = 6;
    private String deviceId_;
    /**
     * <code>optional string deviceId = 6;</code>
     */
    public String getDeviceId() {
      return deviceId_;
    }
    /**
     * <code>optional string deviceId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
    }
    /**
     * <code>optional string deviceId = 6;</code>
     */
    private void setDeviceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
    }
    /**
     * <code>optional string deviceId = 6;</code>
     */
    private void clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
    }
    /**
     * <code>optional string deviceId = 6;</code>
     */
    private void setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value.toStringUtf8();
    }

    public static final int PUSHTOKEN_FIELD_NUMBER = 7;
    private String pushToken_;
    /**
     * <code>optional string pushToken = 7;</code>
     */
    public String getPushToken() {
      return pushToken_;
    }
    /**
     * <code>optional string pushToken = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPushTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pushToken_);
    }
    /**
     * <code>optional string pushToken = 7;</code>
     */
    private void setPushToken(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pushToken_ = value;
    }
    /**
     * <code>optional string pushToken = 7;</code>
     */
    private void clearPushToken() {
      
      pushToken_ = getDefaultInstance().getPushToken();
    }
    /**
     * <code>optional string pushToken = 7;</code>
     */
    private void setPushTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pushToken_ = value.toStringUtf8();
    }

    public static final int IP_FIELD_NUMBER = 8;
    private String ip_;
    /**
     * <code>optional string ip = 8;</code>
     */
    public String getIp() {
      return ip_;
    }
    /**
     * <code>optional string ip = 8;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ip_);
    }
    /**
     * <code>optional string ip = 8;</code>
     */
    private void setIp(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
    }
    /**
     * <code>optional string ip = 8;</code>
     */
    private void clearIp() {
      
      ip_ = getDefaultInstance().getIp();
    }
    /**
     * <code>optional string ip = 8;</code>
     */
    private void setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      if (!password_.isEmpty()) {
        output.writeString(3, getPassword());
      }
      if (deviceType_ != JelpProto.DeviceType.UNKNOWN_DEVICE.getNumber()) {
        output.writeEnum(4, deviceType_);
      }
      if (!deviceInfo_.isEmpty()) {
        output.writeString(5, getDeviceInfo());
      }
      if (!deviceId_.isEmpty()) {
        output.writeString(6, getDeviceId());
      }
      if (!pushToken_.isEmpty()) {
        output.writeString(7, getPushToken());
      }
      if (!ip_.isEmpty()) {
        output.writeString(8, getIp());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      if (!password_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPassword());
      }
      if (deviceType_ != JelpProto.DeviceType.UNKNOWN_DEVICE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, deviceType_);
      }
      if (!deviceInfo_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getDeviceInfo());
      }
      if (!deviceId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getDeviceId());
      }
      if (!pushToken_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getPushToken());
      }
      if (!ip_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getIp());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static AddUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AddUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AddUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static AddUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static AddUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AddUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AddUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static AddUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static AddUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static AddUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.AddUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          AddUserRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.AddUserRequest)
        AddUserRequestOrBuilder {
      // Construct using com.brilltech.jelp.entities.AccountProto.AddUserRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .brilltech.jelp.entities.User user = 1;</code>
       */
      public boolean hasUser() {
        return instance.hasUser();
      }
      /**
       * <code>optional .brilltech.jelp.entities.User user = 1;</code>
       */
      public UserProto.User getUser() {
        return instance.getUser();
      }
      /**
       * <code>optional .brilltech.jelp.entities.User user = 1;</code>
       */
      public Builder setUser(UserProto.User value) {
        copyOnWrite();
        instance.setUser(value);
        return this;
        }
      /**
       * <code>optional .brilltech.jelp.entities.User user = 1;</code>
       */
      public Builder setUser(
          UserProto.User.Builder builderForValue) {
        copyOnWrite();
        instance.setUser(builderForValue);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.User user = 1;</code>
       */
      public Builder mergeUser(UserProto.User value) {
        copyOnWrite();
        instance.mergeUser(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.User user = 1;</code>
       */
      public Builder clearUser() {  copyOnWrite();
        instance.clearUser();
        return this;
      }

      /**
       * <code>optional string password = 3;</code>
       */
      public String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPassword(
          String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>optional string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
       */
      public int getDeviceTypeValue() {
        return instance.getDeviceTypeValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
       */
      public Builder setDeviceTypeValue(int value) {
        copyOnWrite();
        instance.setDeviceTypeValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
       */
      public JelpProto.DeviceType getDeviceType() {
        return instance.getDeviceType();
      }
      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
       */
      public Builder setDeviceType(JelpProto.DeviceType value) {
        copyOnWrite();
        instance.setDeviceType(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 4;</code>
       */
      public Builder clearDeviceType() {
        copyOnWrite();
        instance.clearDeviceType();
        return this;
      }

      /**
       * <code>optional string deviceInfo = 5;</code>
       */
      public String getDeviceInfo() {
        return instance.getDeviceInfo();
      }
      /**
       * <code>optional string deviceInfo = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceInfoBytes() {
        return instance.getDeviceInfoBytes();
      }
      /**
       * <code>optional string deviceInfo = 5;</code>
       */
      public Builder setDeviceInfo(
          String value) {
        copyOnWrite();
        instance.setDeviceInfo(value);
        return this;
      }
      /**
       * <code>optional string deviceInfo = 5;</code>
       */
      public Builder clearDeviceInfo() {
        copyOnWrite();
        instance.clearDeviceInfo();
        return this;
      }
      /**
       * <code>optional string deviceInfo = 5;</code>
       */
      public Builder setDeviceInfoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceInfoBytes(value);
        return this;
      }

      /**
       * <code>optional string deviceId = 6;</code>
       */
      public String getDeviceId() {
        return instance.getDeviceId();
      }
      /**
       * <code>optional string deviceId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        return instance.getDeviceIdBytes();
      }
      /**
       * <code>optional string deviceId = 6;</code>
       */
      public Builder setDeviceId(
          String value) {
        copyOnWrite();
        instance.setDeviceId(value);
        return this;
      }
      /**
       * <code>optional string deviceId = 6;</code>
       */
      public Builder clearDeviceId() {
        copyOnWrite();
        instance.clearDeviceId();
        return this;
      }
      /**
       * <code>optional string deviceId = 6;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceIdBytes(value);
        return this;
      }

      /**
       * <code>optional string pushToken = 7;</code>
       */
      public String getPushToken() {
        return instance.getPushToken();
      }
      /**
       * <code>optional string pushToken = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPushTokenBytes() {
        return instance.getPushTokenBytes();
      }
      /**
       * <code>optional string pushToken = 7;</code>
       */
      public Builder setPushToken(
          String value) {
        copyOnWrite();
        instance.setPushToken(value);
        return this;
      }
      /**
       * <code>optional string pushToken = 7;</code>
       */
      public Builder clearPushToken() {
        copyOnWrite();
        instance.clearPushToken();
        return this;
      }
      /**
       * <code>optional string pushToken = 7;</code>
       */
      public Builder setPushTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPushTokenBytes(value);
        return this;
      }

      /**
       * <code>optional string ip = 8;</code>
       */
      public String getIp() {
        return instance.getIp();
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        return instance.getIpBytes();
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public Builder setIp(
          String value) {
        copyOnWrite();
        instance.setIp(value);
        return this;
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public Builder clearIp() {
        copyOnWrite();
        instance.clearIp();
        return this;
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIpBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.AddUserRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new AddUserRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          AddUserRequest other = (AddUserRequest) arg1;
          user_ = visitor.visitMessage(user_, other.user_);
          password_ = visitor.visitString(!password_.isEmpty(), password_,
              !other.password_.isEmpty(), other.password_);
          deviceType_ = visitor.visitInt(deviceType_ != 0, deviceType_,    other.deviceType_ != 0, other.deviceType_);
          deviceInfo_ = visitor.visitString(!deviceInfo_.isEmpty(), deviceInfo_,
              !other.deviceInfo_.isEmpty(), other.deviceInfo_);
          deviceId_ = visitor.visitString(!deviceId_.isEmpty(), deviceId_,
              !other.deviceId_.isEmpty(), other.deviceId_);
          pushToken_ = visitor.visitString(!pushToken_.isEmpty(), pushToken_,
              !other.pushToken_.isEmpty(), other.pushToken_);
          ip_ = visitor.visitString(!ip_.isEmpty(), ip_,
              !other.ip_.isEmpty(), other.ip_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  UserProto.User.Builder subBuilder = null;
                  if (user_ != null) {
                    subBuilder = user_.toBuilder();
                  }
                  user_ = input.readMessage(UserProto.User.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(user_);
                    user_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  password_ = s;
                  break;
                }
                case 32: {
                  int rawValue = input.readEnum();

                  deviceType_ = rawValue;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  deviceInfo_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  deviceId_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  pushToken_ = s;
                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();

                  ip_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (AddUserRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.AddUserRequest)
    private static final AddUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddUserRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static AddUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AddUserRequest> PARSER;

    public static com.google.protobuf.Parser<AddUserRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UpdateUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.UpdateUser)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
     */
    int getUserStatusValue();
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
     */
    JelpProto.UserStatus getUserStatus();

    /**
     * <code>repeated string permissions = 2;</code>
     */
    java.util.List<String>
        getPermissionsList();
    /**
     * <code>repeated string permissions = 2;</code>
     */
    int getPermissionsCount();
    /**
     * <code>repeated string permissions = 2;</code>
     */
    String getPermissions(int index);
    /**
     * <code>repeated string permissions = 2;</code>
     */
    com.google.protobuf.ByteString
        getPermissionsBytes(int index);

    /**
     * <code>optional string userId = 3;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.UpdateUser}
   */
  public  static final class UpdateUser extends
      com.google.protobuf.GeneratedMessageLite<
          UpdateUser, UpdateUser.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.UpdateUser)
      UpdateUserOrBuilder {
    private UpdateUser() {
      permissions_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      userId_ = "";
    }
    private int bitField0_;
    public static final int USERSTATUS_FIELD_NUMBER = 1;
    private int userStatus_;
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
     */
    public int getUserStatusValue() {
      return userStatus_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
     */
    public JelpProto.UserStatus getUserStatus() {
      JelpProto.UserStatus result = JelpProto.UserStatus.forNumber(userStatus_);
      return result == null ? JelpProto.UserStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
     */
    private void setUserStatusValue(int value) {
        userStatus_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
     */
    private void setUserStatus(JelpProto.UserStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      userStatus_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
     */
    private void clearUserStatus() {
      
      userStatus_ = 0;
    }

    public static final int PERMISSIONS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<String> permissions_;
    /**
     * <code>repeated string permissions = 2;</code>
     */
    public java.util.List<String> getPermissionsList() {
      return permissions_;
    }
    /**
     * <code>repeated string permissions = 2;</code>
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated string permissions = 2;</code>
     */
    public String getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated string permissions = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPermissionsBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          permissions_.get(index));
    }
    private void ensurePermissionsIsMutable() {
      if (!permissions_.isModifiable()) {
        permissions_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(permissions_);
       }
    }
    /**
     * <code>repeated string permissions = 2;</code>
     */
    private void setPermissions(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
      permissions_.set(index, value);
    }
    /**
     * <code>repeated string permissions = 2;</code>
     */
    private void addPermissions(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePermissionsIsMutable();
      permissions_.add(value);
    }
    /**
     * <code>repeated string permissions = 2;</code>
     */
    private void addAllPermissions(
        Iterable<String> values) {
      ensurePermissionsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, permissions_);
    }
    /**
     * <code>repeated string permissions = 2;</code>
     */
    private void clearPermissions() {
      permissions_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string permissions = 2;</code>
     */
    private void addPermissionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePermissionsIsMutable();
      permissions_.add(value.toStringUtf8());
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private String userId_;
    /**
     * <code>optional string userId = 3;</code>
     */
    public String getUserId() {
      return userId_;
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void setUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userStatus_ != JelpProto.UserStatus.UNKNOWN_USER_STATUS.getNumber()) {
        output.writeEnum(1, userStatus_);
      }
      for (int i = 0; i < permissions_.size(); i++) {
        output.writeString(2, permissions_.get(i));
      }
      if (!userId_.isEmpty()) {
        output.writeString(3, getUserId());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (userStatus_ != JelpProto.UserStatus.UNKNOWN_USER_STATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, userStatus_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < permissions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(permissions_.get(i));
        }
        size += dataSize;
        size += 1 * getPermissionsList().size();
      }
      if (!userId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getUserId());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static UpdateUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UpdateUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UpdateUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UpdateUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UpdateUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UpdateUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UpdateUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static UpdateUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UpdateUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UpdateUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UpdateUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.UpdateUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UpdateUser, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.UpdateUser)
        UpdateUserOrBuilder {
      // Construct using com.brilltech.jelp.entities.AccountProto.UpdateUser.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
       */
      public int getUserStatusValue() {
        return instance.getUserStatusValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
       */
      public Builder setUserStatusValue(int value) {
        copyOnWrite();
        instance.setUserStatusValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
       */
      public JelpProto.UserStatus getUserStatus() {
        return instance.getUserStatus();
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
       */
      public Builder setUserStatus(JelpProto.UserStatus value) {
        copyOnWrite();
        instance.setUserStatus(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 1;</code>
       */
      public Builder clearUserStatus() {
        copyOnWrite();
        instance.clearUserStatus();
        return this;
      }

      /**
       * <code>repeated string permissions = 2;</code>
       */
      public java.util.List<String>
          getPermissionsList() {
        return java.util.Collections.unmodifiableList(
            instance.getPermissionsList());
      }
      /**
       * <code>repeated string permissions = 2;</code>
       */
      public int getPermissionsCount() {
        return instance.getPermissionsCount();
      }
      /**
       * <code>repeated string permissions = 2;</code>
       */
      public String getPermissions(int index) {
        return instance.getPermissions(index);
      }
      /**
       * <code>repeated string permissions = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPermissionsBytes(int index) {
        return instance.getPermissionsBytes(index);
      }
      /**
       * <code>repeated string permissions = 2;</code>
       */
      public Builder setPermissions(
          int index, String value) {
        copyOnWrite();
        instance.setPermissions(index, value);
        return this;
      }
      /**
       * <code>repeated string permissions = 2;</code>
       */
      public Builder addPermissions(
          String value) {
        copyOnWrite();
        instance.addPermissions(value);
        return this;
      }
      /**
       * <code>repeated string permissions = 2;</code>
       */
      public Builder addAllPermissions(
          Iterable<String> values) {
        copyOnWrite();
        instance.addAllPermissions(values);
        return this;
      }
      /**
       * <code>repeated string permissions = 2;</code>
       */
      public Builder clearPermissions() {
        copyOnWrite();
        instance.clearPermissions();
        return this;
      }
      /**
       * <code>repeated string permissions = 2;</code>
       */
      public Builder addPermissionsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addPermissionsBytes(value);
        return this;
      }

      /**
       * <code>optional string userId = 3;</code>
       */
      public String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserId(
          String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.UpdateUser)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UpdateUser();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          permissions_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          UpdateUser other = (UpdateUser) arg1;
          userStatus_ = visitor.visitInt(userStatus_ != 0, userStatus_,    other.userStatus_ != 0, other.userStatus_);
          permissions_= visitor.visitList(permissions_, other.permissions_);
          userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
              !other.userId_.isEmpty(), other.userId_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();

                  userStatus_ = rawValue;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();
                  if (!permissions_.isModifiable()) {
                    permissions_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(permissions_);
                  }
                  permissions_.add(s);
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  userId_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (UpdateUser.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.UpdateUser)
    private static final UpdateUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UpdateUser();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static UpdateUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UpdateUser> PARSER;

    public static com.google.protobuf.Parser<UpdateUser> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PasswordChangeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.PasswordChangeRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string oldPassword = 1;</code>
     */
    String getOldPassword();
    /**
     * <code>optional string oldPassword = 1;</code>
     */
    com.google.protobuf.ByteString
        getOldPasswordBytes();

    /**
     * <code>optional string newPassword = 2;</code>
     */
    String getNewPassword();
    /**
     * <code>optional string newPassword = 2;</code>
     */
    com.google.protobuf.ByteString
        getNewPasswordBytes();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.PasswordChangeRequest}
   */
  public  static final class PasswordChangeRequest extends
      com.google.protobuf.GeneratedMessageLite<
          PasswordChangeRequest, PasswordChangeRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.PasswordChangeRequest)
      PasswordChangeRequestOrBuilder {
    private PasswordChangeRequest() {
      oldPassword_ = "";
      newPassword_ = "";
    }
    public static final int OLDPASSWORD_FIELD_NUMBER = 1;
    private String oldPassword_;
    /**
     * <code>optional string oldPassword = 1;</code>
     */
    public String getOldPassword() {
      return oldPassword_;
    }
    /**
     * <code>optional string oldPassword = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOldPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(oldPassword_);
    }
    /**
     * <code>optional string oldPassword = 1;</code>
     */
    private void setOldPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      oldPassword_ = value;
    }
    /**
     * <code>optional string oldPassword = 1;</code>
     */
    private void clearOldPassword() {
      
      oldPassword_ = getDefaultInstance().getOldPassword();
    }
    /**
     * <code>optional string oldPassword = 1;</code>
     */
    private void setOldPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      oldPassword_ = value.toStringUtf8();
    }

    public static final int NEWPASSWORD_FIELD_NUMBER = 2;
    private String newPassword_;
    /**
     * <code>optional string newPassword = 2;</code>
     */
    public String getNewPassword() {
      return newPassword_;
    }
    /**
     * <code>optional string newPassword = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(newPassword_);
    }
    /**
     * <code>optional string newPassword = 2;</code>
     */
    private void setNewPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newPassword_ = value;
    }
    /**
     * <code>optional string newPassword = 2;</code>
     */
    private void clearNewPassword() {
      
      newPassword_ = getDefaultInstance().getNewPassword();
    }
    /**
     * <code>optional string newPassword = 2;</code>
     */
    private void setNewPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newPassword_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!oldPassword_.isEmpty()) {
        output.writeString(1, getOldPassword());
      }
      if (!newPassword_.isEmpty()) {
        output.writeString(2, getNewPassword());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!oldPassword_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getOldPassword());
      }
      if (!newPassword_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNewPassword());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static PasswordChangeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PasswordChangeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PasswordChangeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PasswordChangeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PasswordChangeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static PasswordChangeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static PasswordChangeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static PasswordChangeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static PasswordChangeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static PasswordChangeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PasswordChangeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.PasswordChangeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          PasswordChangeRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.PasswordChangeRequest)
        PasswordChangeRequestOrBuilder {
      // Construct using com.brilltech.jelp.entities.AccountProto.PasswordChangeRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string oldPassword = 1;</code>
       */
      public String getOldPassword() {
        return instance.getOldPassword();
      }
      /**
       * <code>optional string oldPassword = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOldPasswordBytes() {
        return instance.getOldPasswordBytes();
      }
      /**
       * <code>optional string oldPassword = 1;</code>
       */
      public Builder setOldPassword(
          String value) {
        copyOnWrite();
        instance.setOldPassword(value);
        return this;
      }
      /**
       * <code>optional string oldPassword = 1;</code>
       */
      public Builder clearOldPassword() {
        copyOnWrite();
        instance.clearOldPassword();
        return this;
      }
      /**
       * <code>optional string oldPassword = 1;</code>
       */
      public Builder setOldPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOldPasswordBytes(value);
        return this;
      }

      /**
       * <code>optional string newPassword = 2;</code>
       */
      public String getNewPassword() {
        return instance.getNewPassword();
      }
      /**
       * <code>optional string newPassword = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNewPasswordBytes() {
        return instance.getNewPasswordBytes();
      }
      /**
       * <code>optional string newPassword = 2;</code>
       */
      public Builder setNewPassword(
          String value) {
        copyOnWrite();
        instance.setNewPassword(value);
        return this;
      }
      /**
       * <code>optional string newPassword = 2;</code>
       */
      public Builder clearNewPassword() {
        copyOnWrite();
        instance.clearNewPassword();
        return this;
      }
      /**
       * <code>optional string newPassword = 2;</code>
       */
      public Builder setNewPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNewPasswordBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.PasswordChangeRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new PasswordChangeRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          PasswordChangeRequest other = (PasswordChangeRequest) arg1;
          oldPassword_ = visitor.visitString(!oldPassword_.isEmpty(), oldPassword_,
              !other.oldPassword_.isEmpty(), other.oldPassword_);
          newPassword_ = visitor.visitString(!newPassword_.isEmpty(), newPassword_,
              !other.newPassword_.isEmpty(), other.newPassword_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  oldPassword_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  newPassword_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (PasswordChangeRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.PasswordChangeRequest)
    private static final PasswordChangeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PasswordChangeRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static PasswordChangeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PasswordChangeRequest> PARSER;

    public static com.google.protobuf.Parser<PasswordChangeRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PasswordResetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.PasswordReset)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string email = 1;</code>
     */
    String getEmail();
    /**
     * <code>optional string email = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string newPassword = 2;</code>
     */
    String getNewPassword();
    /**
     * <code>optional string newPassword = 2;</code>
     */
    com.google.protobuf.ByteString
        getNewPasswordBytes();

    /**
     * <code>optional string userId = 3;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional int32 code = 4;</code>
     */
    int getCode();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.PasswordReset}
   */
  public  static final class PasswordReset extends
      com.google.protobuf.GeneratedMessageLite<
          PasswordReset, PasswordReset.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.PasswordReset)
      PasswordResetOrBuilder {
    private PasswordReset() {
      email_ = "";
      newPassword_ = "";
      userId_ = "";
    }
    public static final int EMAIL_FIELD_NUMBER = 1;
    private String email_;
    /**
     * <code>optional string email = 1;</code>
     */
    public String getEmail() {
      return email_;
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>optional string email = 1;</code>
     */
    private void setEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
    }
    /**
     * <code>optional string email = 1;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>optional string email = 1;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value.toStringUtf8();
    }

    public static final int NEWPASSWORD_FIELD_NUMBER = 2;
    private String newPassword_;
    /**
     * <code>optional string newPassword = 2;</code>
     */
    public String getNewPassword() {
      return newPassword_;
    }
    /**
     * <code>optional string newPassword = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(newPassword_);
    }
    /**
     * <code>optional string newPassword = 2;</code>
     */
    private void setNewPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newPassword_ = value;
    }
    /**
     * <code>optional string newPassword = 2;</code>
     */
    private void clearNewPassword() {
      
      newPassword_ = getDefaultInstance().getNewPassword();
    }
    /**
     * <code>optional string newPassword = 2;</code>
     */
    private void setNewPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newPassword_ = value.toStringUtf8();
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private String userId_;
    /**
     * <code>optional string userId = 3;</code>
     */
    public String getUserId() {
      return userId_;
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void setUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value.toStringUtf8();
    }

    public static final int CODE_FIELD_NUMBER = 4;
    private int code_;
    /**
     * <code>optional int32 code = 4;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>optional int32 code = 4;</code>
     */
    private void setCode(int value) {
      
      code_ = value;
    }
    /**
     * <code>optional int32 code = 4;</code>
     */
    private void clearCode() {
      
      code_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!email_.isEmpty()) {
        output.writeString(1, getEmail());
      }
      if (!newPassword_.isEmpty()) {
        output.writeString(2, getNewPassword());
      }
      if (!userId_.isEmpty()) {
        output.writeString(3, getUserId());
      }
      if (code_ != 0) {
        output.writeInt32(4, code_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!email_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getEmail());
      }
      if (!newPassword_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNewPassword());
      }
      if (!userId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getUserId());
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, code_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static PasswordReset parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PasswordReset parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PasswordReset parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PasswordReset parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PasswordReset parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static PasswordReset parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static PasswordReset parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static PasswordReset parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static PasswordReset parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static PasswordReset parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PasswordReset prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.PasswordReset}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          PasswordReset, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.PasswordReset)
        PasswordResetOrBuilder {
      // Construct using com.brilltech.jelp.entities.AccountProto.PasswordReset.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string email = 1;</code>
       */
      public String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public Builder setEmail(
          String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>optional string newPassword = 2;</code>
       */
      public String getNewPassword() {
        return instance.getNewPassword();
      }
      /**
       * <code>optional string newPassword = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNewPasswordBytes() {
        return instance.getNewPasswordBytes();
      }
      /**
       * <code>optional string newPassword = 2;</code>
       */
      public Builder setNewPassword(
          String value) {
        copyOnWrite();
        instance.setNewPassword(value);
        return this;
      }
      /**
       * <code>optional string newPassword = 2;</code>
       */
      public Builder clearNewPassword() {
        copyOnWrite();
        instance.clearNewPassword();
        return this;
      }
      /**
       * <code>optional string newPassword = 2;</code>
       */
      public Builder setNewPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNewPasswordBytes(value);
        return this;
      }

      /**
       * <code>optional string userId = 3;</code>
       */
      public String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserId(
          String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      /**
       * <code>optional int32 code = 4;</code>
       */
      public int getCode() {
        return instance.getCode();
      }
      /**
       * <code>optional int32 code = 4;</code>
       */
      public Builder setCode(int value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <code>optional int32 code = 4;</code>
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.PasswordReset)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new PasswordReset();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          PasswordReset other = (PasswordReset) arg1;
          email_ = visitor.visitString(!email_.isEmpty(), email_,
              !other.email_.isEmpty(), other.email_);
          newPassword_ = visitor.visitString(!newPassword_.isEmpty(), newPassword_,
              !other.newPassword_.isEmpty(), other.newPassword_);
          userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
              !other.userId_.isEmpty(), other.userId_);
          code_ = visitor.visitInt(code_ != 0, code_,
              other.code_ != 0, other.code_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  email_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  newPassword_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  userId_ = s;
                  break;
                }
                case 32: {

                  code_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (PasswordReset.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.PasswordReset)
    private static final PasswordReset DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PasswordReset();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static PasswordReset getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PasswordReset> PARSER;

    public static com.google.protobuf.Parser<PasswordReset> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EmailVerificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.EmailVerification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string refId = 1;</code>
     */
    String getRefId();
    /**
     * <code>optional string refId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRefIdBytes();

    /**
     * <code>optional string email = 2;</code>
     */
    String getEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional int32 sixDigitRandomNumber = 3;</code>
     */
    int getSixDigitRandomNumber();

    /**
     * <code>optional int64 timestamp = 4;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.EmailVerification}
   */
  public  static final class EmailVerification extends
      com.google.protobuf.GeneratedMessageLite<
          EmailVerification, EmailVerification.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.EmailVerification)
      EmailVerificationOrBuilder {
    private EmailVerification() {
      refId_ = "";
      email_ = "";
    }
    public static final int REFID_FIELD_NUMBER = 1;
    private String refId_;
    /**
     * <code>optional string refId = 1;</code>
     */
    public String getRefId() {
      return refId_;
    }
    /**
     * <code>optional string refId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRefIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(refId_);
    }
    /**
     * <code>optional string refId = 1;</code>
     */
    private void setRefId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      refId_ = value;
    }
    /**
     * <code>optional string refId = 1;</code>
     */
    private void clearRefId() {
      
      refId_ = getDefaultInstance().getRefId();
    }
    /**
     * <code>optional string refId = 1;</code>
     */
    private void setRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      refId_ = value.toStringUtf8();
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private String email_;
    /**
     * <code>optional string email = 2;</code>
     */
    public String getEmail() {
      return email_;
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void setEmail(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>optional string email = 2;</code>
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value.toStringUtf8();
    }

    public static final int SIXDIGITRANDOMNUMBER_FIELD_NUMBER = 3;
    private int sixDigitRandomNumber_;
    /**
     * <code>optional int32 sixDigitRandomNumber = 3;</code>
     */
    public int getSixDigitRandomNumber() {
      return sixDigitRandomNumber_;
    }
    /**
     * <code>optional int32 sixDigitRandomNumber = 3;</code>
     */
    private void setSixDigitRandomNumber(int value) {
      
      sixDigitRandomNumber_ = value;
    }
    /**
     * <code>optional int32 sixDigitRandomNumber = 3;</code>
     */
    private void clearSixDigitRandomNumber() {
      
      sixDigitRandomNumber_ = 0;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional int64 timestamp = 4;</code>
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <code>optional int64 timestamp = 4;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!refId_.isEmpty()) {
        output.writeString(1, getRefId());
      }
      if (!email_.isEmpty()) {
        output.writeString(2, getEmail());
      }
      if (sixDigitRandomNumber_ != 0) {
        output.writeInt32(3, sixDigitRandomNumber_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!refId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getRefId());
      }
      if (!email_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEmail());
      }
      if (sixDigitRandomNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sixDigitRandomNumber_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static EmailVerification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmailVerification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmailVerification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmailVerification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmailVerification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EmailVerification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EmailVerification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static EmailVerification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EmailVerification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EmailVerification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmailVerification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.EmailVerification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          EmailVerification, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.EmailVerification)
        EmailVerificationOrBuilder {
      // Construct using com.brilltech.jelp.entities.AccountProto.EmailVerification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string refId = 1;</code>
       */
      public String getRefId() {
        return instance.getRefId();
      }
      /**
       * <code>optional string refId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRefIdBytes() {
        return instance.getRefIdBytes();
      }
      /**
       * <code>optional string refId = 1;</code>
       */
      public Builder setRefId(
          String value) {
        copyOnWrite();
        instance.setRefId(value);
        return this;
      }
      /**
       * <code>optional string refId = 1;</code>
       */
      public Builder clearRefId() {
        copyOnWrite();
        instance.clearRefId();
        return this;
      }
      /**
       * <code>optional string refId = 1;</code>
       */
      public Builder setRefIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRefIdBytes(value);
        return this;
      }

      /**
       * <code>optional string email = 2;</code>
       */
      public String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmail(
          String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>optional int32 sixDigitRandomNumber = 3;</code>
       */
      public int getSixDigitRandomNumber() {
        return instance.getSixDigitRandomNumber();
      }
      /**
       * <code>optional int32 sixDigitRandomNumber = 3;</code>
       */
      public Builder setSixDigitRandomNumber(int value) {
        copyOnWrite();
        instance.setSixDigitRandomNumber(value);
        return this;
      }
      /**
       * <code>optional int32 sixDigitRandomNumber = 3;</code>
       */
      public Builder clearSixDigitRandomNumber() {
        copyOnWrite();
        instance.clearSixDigitRandomNumber();
        return this;
      }

      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.EmailVerification)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new EmailVerification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          EmailVerification other = (EmailVerification) arg1;
          refId_ = visitor.visitString(!refId_.isEmpty(), refId_,
              !other.refId_.isEmpty(), other.refId_);
          email_ = visitor.visitString(!email_.isEmpty(), email_,
              !other.email_.isEmpty(), other.email_);
          sixDigitRandomNumber_ = visitor.visitInt(sixDigitRandomNumber_ != 0, sixDigitRandomNumber_,
              other.sixDigitRandomNumber_ != 0, other.sixDigitRandomNumber_);
          timestamp_ = visitor.visitLong(timestamp_ != 0L, timestamp_,
              other.timestamp_ != 0L, other.timestamp_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  refId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  email_ = s;
                  break;
                }
                case 24: {

                  sixDigitRandomNumber_ = input.readInt32();
                  break;
                }
                case 32: {

                  timestamp_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (EmailVerification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.EmailVerification)
    private static final EmailVerification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmailVerification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static EmailVerification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EmailVerification> PARSER;

    public static com.google.protobuf.Parser<EmailVerification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
