// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emergency.proto

package com.brilltech.jelp.entities;

public final class EmergencyProto {
  private EmergencyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface EmergencyRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.EmergencyRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string emergencyRequestId = 1;</code>
     */
    String getEmergencyRequestId();
    /**
     * <code>optional string emergencyRequestId = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmergencyRequestIdBytes();

    /**
     * <code>optional string userId = 2;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
     */
    int getRequestTypeValue();
    /**
     * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
     */
    JelpProto.RequestType getRequestType();

    /**
     * <code>optional double locationLat = 5;</code>
     */
    double getLocationLat();

    /**
     * <code>optional double locationLng = 6;</code>
     */
    double getLocationLng();

    /**
     * <code>optional int64 createdAt = 7;</code>
     */
    long getCreatedAt();

    /**
     * <code>optional int64 updatedAt = 8;</code>
     */
    long getUpdatedAt();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.EmergencyRequest}
   */
  public  static final class EmergencyRequest extends
      com.google.protobuf.GeneratedMessageLite<
          EmergencyRequest, EmergencyRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.EmergencyRequest)
      EmergencyRequestOrBuilder {
    private EmergencyRequest() {
      emergencyRequestId_ = "";
      userId_ = "";
    }
    public static final int EMERGENCYREQUESTID_FIELD_NUMBER = 1;
    private String emergencyRequestId_;
    /**
     * <code>optional string emergencyRequestId = 1;</code>
     */
    public String getEmergencyRequestId() {
      return emergencyRequestId_;
    }
    /**
     * <code>optional string emergencyRequestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmergencyRequestIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emergencyRequestId_);
    }
    /**
     * <code>optional string emergencyRequestId = 1;</code>
     */
    private void setEmergencyRequestId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emergencyRequestId_ = value;
    }
    /**
     * <code>optional string emergencyRequestId = 1;</code>
     */
    private void clearEmergencyRequestId() {
      
      emergencyRequestId_ = getDefaultInstance().getEmergencyRequestId();
    }
    /**
     * <code>optional string emergencyRequestId = 1;</code>
     */
    private void setEmergencyRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emergencyRequestId_ = value.toStringUtf8();
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private String userId_;
    /**
     * <code>optional string userId = 2;</code>
     */
    public String getUserId() {
      return userId_;
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    private void setUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    private void clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value.toStringUtf8();
    }

    public static final int REQUESTTYPE_FIELD_NUMBER = 4;
    private int requestType_;
    /**
     * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
     */
    public JelpProto.RequestType getRequestType() {
      JelpProto.RequestType result = JelpProto.RequestType.forNumber(requestType_);
      return result == null ? JelpProto.RequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
     */
    private void setRequestTypeValue(int value) {
        requestType_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
     */
    private void setRequestType(JelpProto.RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      requestType_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
     */
    private void clearRequestType() {
      
      requestType_ = 0;
    }

    public static final int LOCATIONLAT_FIELD_NUMBER = 5;
    private double locationLat_;
    /**
     * <code>optional double locationLat = 5;</code>
     */
    public double getLocationLat() {
      return locationLat_;
    }
    /**
     * <code>optional double locationLat = 5;</code>
     */
    private void setLocationLat(double value) {
      
      locationLat_ = value;
    }
    /**
     * <code>optional double locationLat = 5;</code>
     */
    private void clearLocationLat() {
      
      locationLat_ = 0D;
    }

    public static final int LOCATIONLNG_FIELD_NUMBER = 6;
    private double locationLng_;
    /**
     * <code>optional double locationLng = 6;</code>
     */
    public double getLocationLng() {
      return locationLng_;
    }
    /**
     * <code>optional double locationLng = 6;</code>
     */
    private void setLocationLng(double value) {
      
      locationLng_ = value;
    }
    /**
     * <code>optional double locationLng = 6;</code>
     */
    private void clearLocationLng() {
      
      locationLng_ = 0D;
    }

    public static final int CREATEDAT_FIELD_NUMBER = 7;
    private long createdAt_;
    /**
     * <code>optional int64 createdAt = 7;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>optional int64 createdAt = 7;</code>
     */
    private void setCreatedAt(long value) {
      
      createdAt_ = value;
    }
    /**
     * <code>optional int64 createdAt = 7;</code>
     */
    private void clearCreatedAt() {
      
      createdAt_ = 0L;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 8;
    private long updatedAt_;
    /**
     * <code>optional int64 updatedAt = 8;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>optional int64 updatedAt = 8;</code>
     */
    private void setUpdatedAt(long value) {
      
      updatedAt_ = value;
    }
    /**
     * <code>optional int64 updatedAt = 8;</code>
     */
    private void clearUpdatedAt() {
      
      updatedAt_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!emergencyRequestId_.isEmpty()) {
        output.writeString(1, getEmergencyRequestId());
      }
      if (!userId_.isEmpty()) {
        output.writeString(2, getUserId());
      }
      if (requestType_ != JelpProto.RequestType.UNKNOWN_REQUEST_TYPE.getNumber()) {
        output.writeEnum(4, requestType_);
      }
      if (locationLat_ != 0D) {
        output.writeDouble(5, locationLat_);
      }
      if (locationLng_ != 0D) {
        output.writeDouble(6, locationLng_);
      }
      if (createdAt_ != 0L) {
        output.writeInt64(7, createdAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(8, updatedAt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!emergencyRequestId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getEmergencyRequestId());
      }
      if (!userId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getUserId());
      }
      if (requestType_ != JelpProto.RequestType.UNKNOWN_REQUEST_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, requestType_);
      }
      if (locationLat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, locationLat_);
      }
      if (locationLng_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, locationLng_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, createdAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, updatedAt_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static EmergencyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmergencyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmergencyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmergencyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmergencyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EmergencyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EmergencyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static EmergencyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EmergencyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EmergencyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmergencyRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.EmergencyRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          EmergencyRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.EmergencyRequest)
        EmergencyRequestOrBuilder {
      // Construct using com.brilltech.jelp.entities.EmergencyProto.EmergencyRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string emergencyRequestId = 1;</code>
       */
      public String getEmergencyRequestId() {
        return instance.getEmergencyRequestId();
      }
      /**
       * <code>optional string emergencyRequestId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmergencyRequestIdBytes() {
        return instance.getEmergencyRequestIdBytes();
      }
      /**
       * <code>optional string emergencyRequestId = 1;</code>
       */
      public Builder setEmergencyRequestId(
          String value) {
        copyOnWrite();
        instance.setEmergencyRequestId(value);
        return this;
      }
      /**
       * <code>optional string emergencyRequestId = 1;</code>
       */
      public Builder clearEmergencyRequestId() {
        copyOnWrite();
        instance.clearEmergencyRequestId();
        return this;
      }
      /**
       * <code>optional string emergencyRequestId = 1;</code>
       */
      public Builder setEmergencyRequestIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmergencyRequestIdBytes(value);
        return this;
      }

      /**
       * <code>optional string userId = 2;</code>
       */
      public String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserId(
          String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
       */
      public int getRequestTypeValue() {
        return instance.getRequestTypeValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
       */
      public Builder setRequestTypeValue(int value) {
        copyOnWrite();
        instance.setRequestTypeValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
       */
      public JelpProto.RequestType getRequestType() {
        return instance.getRequestType();
      }
      /**
       * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
       */
      public Builder setRequestType(JelpProto.RequestType value) {
        copyOnWrite();
        instance.setRequestType(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.RequestType requestType = 4;</code>
       */
      public Builder clearRequestType() {
        copyOnWrite();
        instance.clearRequestType();
        return this;
      }

      /**
       * <code>optional double locationLat = 5;</code>
       */
      public double getLocationLat() {
        return instance.getLocationLat();
      }
      /**
       * <code>optional double locationLat = 5;</code>
       */
      public Builder setLocationLat(double value) {
        copyOnWrite();
        instance.setLocationLat(value);
        return this;
      }
      /**
       * <code>optional double locationLat = 5;</code>
       */
      public Builder clearLocationLat() {
        copyOnWrite();
        instance.clearLocationLat();
        return this;
      }

      /**
       * <code>optional double locationLng = 6;</code>
       */
      public double getLocationLng() {
        return instance.getLocationLng();
      }
      /**
       * <code>optional double locationLng = 6;</code>
       */
      public Builder setLocationLng(double value) {
        copyOnWrite();
        instance.setLocationLng(value);
        return this;
      }
      /**
       * <code>optional double locationLng = 6;</code>
       */
      public Builder clearLocationLng() {
        copyOnWrite();
        instance.clearLocationLng();
        return this;
      }

      /**
       * <code>optional int64 createdAt = 7;</code>
       */
      public long getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>optional int64 createdAt = 7;</code>
       */
      public Builder setCreatedAt(long value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 createdAt = 7;</code>
       */
      public Builder clearCreatedAt() {
        copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>optional int64 updatedAt = 8;</code>
       */
      public long getUpdatedAt() {
        return instance.getUpdatedAt();
      }
      /**
       * <code>optional int64 updatedAt = 8;</code>
       */
      public Builder setUpdatedAt(long value) {
        copyOnWrite();
        instance.setUpdatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 updatedAt = 8;</code>
       */
      public Builder clearUpdatedAt() {
        copyOnWrite();
        instance.clearUpdatedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.EmergencyRequest)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new EmergencyRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          EmergencyRequest other = (EmergencyRequest) arg1;
          emergencyRequestId_ = visitor.visitString(!emergencyRequestId_.isEmpty(), emergencyRequestId_,
              !other.emergencyRequestId_.isEmpty(), other.emergencyRequestId_);
          userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
              !other.userId_.isEmpty(), other.userId_);
          requestType_ = visitor.visitInt(requestType_ != 0, requestType_,    other.requestType_ != 0, other.requestType_);
          locationLat_ = visitor.visitDouble(locationLat_ != 0D, locationLat_,
              other.locationLat_ != 0D, other.locationLat_);
          locationLng_ = visitor.visitDouble(locationLng_ != 0D, locationLng_,
              other.locationLng_ != 0D, other.locationLng_);
          createdAt_ = visitor.visitLong(createdAt_ != 0L, createdAt_,
              other.createdAt_ != 0L, other.createdAt_);
          updatedAt_ = visitor.visitLong(updatedAt_ != 0L, updatedAt_,
              other.updatedAt_ != 0L, other.updatedAt_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  emergencyRequestId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  userId_ = s;
                  break;
                }
                case 32: {
                  int rawValue = input.readEnum();

                  requestType_ = rawValue;
                  break;
                }
                case 41: {

                  locationLat_ = input.readDouble();
                  break;
                }
                case 49: {

                  locationLng_ = input.readDouble();
                  break;
                }
                case 56: {

                  createdAt_ = input.readInt64();
                  break;
                }
                case 64: {

                  updatedAt_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (EmergencyRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.EmergencyRequest)
    private static final EmergencyRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmergencyRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static EmergencyRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EmergencyRequest> PARSER;

    public static com.google.protobuf.Parser<EmergencyRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EmergencyResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.EmergencyResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string emergencyResponseId = 1;</code>
     */
    String getEmergencyResponseId();
    /**
     * <code>optional string emergencyResponseId = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmergencyResponseIdBytes();

    /**
     * <code>optional string emergencyRequestId = 2;</code>
     */
    String getEmergencyRequestId();
    /**
     * <code>optional string emergencyRequestId = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmergencyRequestIdBytes();

    /**
     * <code>optional string userId = 3;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
     */
    int getResponseTypeValue();
    /**
     * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
     */
    JelpProto.ResponseType getResponseType();

    /**
     * <code>optional double locationLat = 6;</code>
     */
    double getLocationLat();

    /**
     * <code>optional double locationLng = 7;</code>
     */
    double getLocationLng();

    /**
     * <code>optional int64 createdAt = 8;</code>
     */
    long getCreatedAt();

    /**
     * <code>optional int64 updatedAt = 9;</code>
     */
    long getUpdatedAt();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.EmergencyResponse}
   */
  public  static final class EmergencyResponse extends
      com.google.protobuf.GeneratedMessageLite<
          EmergencyResponse, EmergencyResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.EmergencyResponse)
      EmergencyResponseOrBuilder {
    private EmergencyResponse() {
      emergencyResponseId_ = "";
      emergencyRequestId_ = "";
      userId_ = "";
    }
    public static final int EMERGENCYRESPONSEID_FIELD_NUMBER = 1;
    private String emergencyResponseId_;
    /**
     * <code>optional string emergencyResponseId = 1;</code>
     */
    public String getEmergencyResponseId() {
      return emergencyResponseId_;
    }
    /**
     * <code>optional string emergencyResponseId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmergencyResponseIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emergencyResponseId_);
    }
    /**
     * <code>optional string emergencyResponseId = 1;</code>
     */
    private void setEmergencyResponseId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emergencyResponseId_ = value;
    }
    /**
     * <code>optional string emergencyResponseId = 1;</code>
     */
    private void clearEmergencyResponseId() {
      
      emergencyResponseId_ = getDefaultInstance().getEmergencyResponseId();
    }
    /**
     * <code>optional string emergencyResponseId = 1;</code>
     */
    private void setEmergencyResponseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emergencyResponseId_ = value.toStringUtf8();
    }

    public static final int EMERGENCYREQUESTID_FIELD_NUMBER = 2;
    private String emergencyRequestId_;
    /**
     * <code>optional string emergencyRequestId = 2;</code>
     */
    public String getEmergencyRequestId() {
      return emergencyRequestId_;
    }
    /**
     * <code>optional string emergencyRequestId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmergencyRequestIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emergencyRequestId_);
    }
    /**
     * <code>optional string emergencyRequestId = 2;</code>
     */
    private void setEmergencyRequestId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emergencyRequestId_ = value;
    }
    /**
     * <code>optional string emergencyRequestId = 2;</code>
     */
    private void clearEmergencyRequestId() {
      
      emergencyRequestId_ = getDefaultInstance().getEmergencyRequestId();
    }
    /**
     * <code>optional string emergencyRequestId = 2;</code>
     */
    private void setEmergencyRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emergencyRequestId_ = value.toStringUtf8();
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private String userId_;
    /**
     * <code>optional string userId = 3;</code>
     */
    public String getUserId() {
      return userId_;
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void setUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>optional string userId = 3;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value.toStringUtf8();
    }

    public static final int RESPONSETYPE_FIELD_NUMBER = 5;
    private int responseType_;
    /**
     * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
     */
    public int getResponseTypeValue() {
      return responseType_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
     */
    public JelpProto.ResponseType getResponseType() {
      JelpProto.ResponseType result = JelpProto.ResponseType.forNumber(responseType_);
      return result == null ? JelpProto.ResponseType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
     */
    private void setResponseTypeValue(int value) {
        responseType_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
     */
    private void setResponseType(JelpProto.ResponseType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      responseType_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
     */
    private void clearResponseType() {
      
      responseType_ = 0;
    }

    public static final int LOCATIONLAT_FIELD_NUMBER = 6;
    private double locationLat_;
    /**
     * <code>optional double locationLat = 6;</code>
     */
    public double getLocationLat() {
      return locationLat_;
    }
    /**
     * <code>optional double locationLat = 6;</code>
     */
    private void setLocationLat(double value) {
      
      locationLat_ = value;
    }
    /**
     * <code>optional double locationLat = 6;</code>
     */
    private void clearLocationLat() {
      
      locationLat_ = 0D;
    }

    public static final int LOCATIONLNG_FIELD_NUMBER = 7;
    private double locationLng_;
    /**
     * <code>optional double locationLng = 7;</code>
     */
    public double getLocationLng() {
      return locationLng_;
    }
    /**
     * <code>optional double locationLng = 7;</code>
     */
    private void setLocationLng(double value) {
      
      locationLng_ = value;
    }
    /**
     * <code>optional double locationLng = 7;</code>
     */
    private void clearLocationLng() {
      
      locationLng_ = 0D;
    }

    public static final int CREATEDAT_FIELD_NUMBER = 8;
    private long createdAt_;
    /**
     * <code>optional int64 createdAt = 8;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>optional int64 createdAt = 8;</code>
     */
    private void setCreatedAt(long value) {
      
      createdAt_ = value;
    }
    /**
     * <code>optional int64 createdAt = 8;</code>
     */
    private void clearCreatedAt() {
      
      createdAt_ = 0L;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 9;
    private long updatedAt_;
    /**
     * <code>optional int64 updatedAt = 9;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>optional int64 updatedAt = 9;</code>
     */
    private void setUpdatedAt(long value) {
      
      updatedAt_ = value;
    }
    /**
     * <code>optional int64 updatedAt = 9;</code>
     */
    private void clearUpdatedAt() {
      
      updatedAt_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!emergencyResponseId_.isEmpty()) {
        output.writeString(1, getEmergencyResponseId());
      }
      if (!emergencyRequestId_.isEmpty()) {
        output.writeString(2, getEmergencyRequestId());
      }
      if (!userId_.isEmpty()) {
        output.writeString(3, getUserId());
      }
      if (responseType_ != JelpProto.ResponseType.UNKNOWN_RESPONSE_TYPE.getNumber()) {
        output.writeEnum(5, responseType_);
      }
      if (locationLat_ != 0D) {
        output.writeDouble(6, locationLat_);
      }
      if (locationLng_ != 0D) {
        output.writeDouble(7, locationLng_);
      }
      if (createdAt_ != 0L) {
        output.writeInt64(8, createdAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(9, updatedAt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!emergencyResponseId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getEmergencyResponseId());
      }
      if (!emergencyRequestId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEmergencyRequestId());
      }
      if (!userId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getUserId());
      }
      if (responseType_ != JelpProto.ResponseType.UNKNOWN_RESPONSE_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, responseType_);
      }
      if (locationLat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, locationLat_);
      }
      if (locationLng_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, locationLng_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, createdAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, updatedAt_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static EmergencyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmergencyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmergencyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static EmergencyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static EmergencyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EmergencyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EmergencyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static EmergencyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static EmergencyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static EmergencyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmergencyResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.EmergencyResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          EmergencyResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.EmergencyResponse)
        EmergencyResponseOrBuilder {
      // Construct using com.brilltech.jelp.entities.EmergencyProto.EmergencyResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string emergencyResponseId = 1;</code>
       */
      public String getEmergencyResponseId() {
        return instance.getEmergencyResponseId();
      }
      /**
       * <code>optional string emergencyResponseId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmergencyResponseIdBytes() {
        return instance.getEmergencyResponseIdBytes();
      }
      /**
       * <code>optional string emergencyResponseId = 1;</code>
       */
      public Builder setEmergencyResponseId(
          String value) {
        copyOnWrite();
        instance.setEmergencyResponseId(value);
        return this;
      }
      /**
       * <code>optional string emergencyResponseId = 1;</code>
       */
      public Builder clearEmergencyResponseId() {
        copyOnWrite();
        instance.clearEmergencyResponseId();
        return this;
      }
      /**
       * <code>optional string emergencyResponseId = 1;</code>
       */
      public Builder setEmergencyResponseIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmergencyResponseIdBytes(value);
        return this;
      }

      /**
       * <code>optional string emergencyRequestId = 2;</code>
       */
      public String getEmergencyRequestId() {
        return instance.getEmergencyRequestId();
      }
      /**
       * <code>optional string emergencyRequestId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmergencyRequestIdBytes() {
        return instance.getEmergencyRequestIdBytes();
      }
      /**
       * <code>optional string emergencyRequestId = 2;</code>
       */
      public Builder setEmergencyRequestId(
          String value) {
        copyOnWrite();
        instance.setEmergencyRequestId(value);
        return this;
      }
      /**
       * <code>optional string emergencyRequestId = 2;</code>
       */
      public Builder clearEmergencyRequestId() {
        copyOnWrite();
        instance.clearEmergencyRequestId();
        return this;
      }
      /**
       * <code>optional string emergencyRequestId = 2;</code>
       */
      public Builder setEmergencyRequestIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmergencyRequestIdBytes(value);
        return this;
      }

      /**
       * <code>optional string userId = 3;</code>
       */
      public String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserId(
          String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>optional string userId = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
       */
      public int getResponseTypeValue() {
        return instance.getResponseTypeValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
       */
      public Builder setResponseTypeValue(int value) {
        copyOnWrite();
        instance.setResponseTypeValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
       */
      public JelpProto.ResponseType getResponseType() {
        return instance.getResponseType();
      }
      /**
       * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
       */
      public Builder setResponseType(JelpProto.ResponseType value) {
        copyOnWrite();
        instance.setResponseType(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.ResponseType responseType = 5;</code>
       */
      public Builder clearResponseType() {
        copyOnWrite();
        instance.clearResponseType();
        return this;
      }

      /**
       * <code>optional double locationLat = 6;</code>
       */
      public double getLocationLat() {
        return instance.getLocationLat();
      }
      /**
       * <code>optional double locationLat = 6;</code>
       */
      public Builder setLocationLat(double value) {
        copyOnWrite();
        instance.setLocationLat(value);
        return this;
      }
      /**
       * <code>optional double locationLat = 6;</code>
       */
      public Builder clearLocationLat() {
        copyOnWrite();
        instance.clearLocationLat();
        return this;
      }

      /**
       * <code>optional double locationLng = 7;</code>
       */
      public double getLocationLng() {
        return instance.getLocationLng();
      }
      /**
       * <code>optional double locationLng = 7;</code>
       */
      public Builder setLocationLng(double value) {
        copyOnWrite();
        instance.setLocationLng(value);
        return this;
      }
      /**
       * <code>optional double locationLng = 7;</code>
       */
      public Builder clearLocationLng() {
        copyOnWrite();
        instance.clearLocationLng();
        return this;
      }

      /**
       * <code>optional int64 createdAt = 8;</code>
       */
      public long getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>optional int64 createdAt = 8;</code>
       */
      public Builder setCreatedAt(long value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 createdAt = 8;</code>
       */
      public Builder clearCreatedAt() {
        copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>optional int64 updatedAt = 9;</code>
       */
      public long getUpdatedAt() {
        return instance.getUpdatedAt();
      }
      /**
       * <code>optional int64 updatedAt = 9;</code>
       */
      public Builder setUpdatedAt(long value) {
        copyOnWrite();
        instance.setUpdatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 updatedAt = 9;</code>
       */
      public Builder clearUpdatedAt() {
        copyOnWrite();
        instance.clearUpdatedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.EmergencyResponse)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new EmergencyResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          EmergencyResponse other = (EmergencyResponse) arg1;
          emergencyResponseId_ = visitor.visitString(!emergencyResponseId_.isEmpty(), emergencyResponseId_,
              !other.emergencyResponseId_.isEmpty(), other.emergencyResponseId_);
          emergencyRequestId_ = visitor.visitString(!emergencyRequestId_.isEmpty(), emergencyRequestId_,
              !other.emergencyRequestId_.isEmpty(), other.emergencyRequestId_);
          userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
              !other.userId_.isEmpty(), other.userId_);
          responseType_ = visitor.visitInt(responseType_ != 0, responseType_,    other.responseType_ != 0, other.responseType_);
          locationLat_ = visitor.visitDouble(locationLat_ != 0D, locationLat_,
              other.locationLat_ != 0D, other.locationLat_);
          locationLng_ = visitor.visitDouble(locationLng_ != 0D, locationLng_,
              other.locationLng_ != 0D, other.locationLng_);
          createdAt_ = visitor.visitLong(createdAt_ != 0L, createdAt_,
              other.createdAt_ != 0L, other.createdAt_);
          updatedAt_ = visitor.visitLong(updatedAt_ != 0L, updatedAt_,
              other.updatedAt_ != 0L, other.updatedAt_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  emergencyResponseId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  emergencyRequestId_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  userId_ = s;
                  break;
                }
                case 40: {
                  int rawValue = input.readEnum();

                  responseType_ = rawValue;
                  break;
                }
                case 49: {

                  locationLat_ = input.readDouble();
                  break;
                }
                case 57: {

                  locationLng_ = input.readDouble();
                  break;
                }
                case 64: {

                  createdAt_ = input.readInt64();
                  break;
                }
                case 72: {

                  updatedAt_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (EmergencyResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.EmergencyResponse)
    private static final EmergencyResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmergencyResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static EmergencyResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<EmergencyResponse> PARSER;

    public static com.google.protobuf.Parser<EmergencyResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UpdateLocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.UpdateLocation)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string senderId = 1;</code>
     */
    String getSenderId();
    /**
     * <code>optional string senderId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <code>optional double locationLat = 2;</code>
     */
    double getLocationLat();

    /**
     * <code>optional double locationLng = 3;</code>
     */
    double getLocationLng();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.UpdateLocation}
   */
  public  static final class UpdateLocation extends
      com.google.protobuf.GeneratedMessageLite<
          UpdateLocation, UpdateLocation.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.UpdateLocation)
      UpdateLocationOrBuilder {
    private UpdateLocation() {
      senderId_ = "";
    }
    public static final int SENDERID_FIELD_NUMBER = 1;
    private String senderId_;
    /**
     * <code>optional string senderId = 1;</code>
     */
    public String getSenderId() {
      return senderId_;
    }
    /**
     * <code>optional string senderId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(senderId_);
    }
    /**
     * <code>optional string senderId = 1;</code>
     */
    private void setSenderId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderId_ = value;
    }
    /**
     * <code>optional string senderId = 1;</code>
     */
    private void clearSenderId() {
      
      senderId_ = getDefaultInstance().getSenderId();
    }
    /**
     * <code>optional string senderId = 1;</code>
     */
    private void setSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderId_ = value.toStringUtf8();
    }

    public static final int LOCATIONLAT_FIELD_NUMBER = 2;
    private double locationLat_;
    /**
     * <code>optional double locationLat = 2;</code>
     */
    public double getLocationLat() {
      return locationLat_;
    }
    /**
     * <code>optional double locationLat = 2;</code>
     */
    private void setLocationLat(double value) {
      
      locationLat_ = value;
    }
    /**
     * <code>optional double locationLat = 2;</code>
     */
    private void clearLocationLat() {
      
      locationLat_ = 0D;
    }

    public static final int LOCATIONLNG_FIELD_NUMBER = 3;
    private double locationLng_;
    /**
     * <code>optional double locationLng = 3;</code>
     */
    public double getLocationLng() {
      return locationLng_;
    }
    /**
     * <code>optional double locationLng = 3;</code>
     */
    private void setLocationLng(double value) {
      
      locationLng_ = value;
    }
    /**
     * <code>optional double locationLng = 3;</code>
     */
    private void clearLocationLng() {
      
      locationLng_ = 0D;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!senderId_.isEmpty()) {
        output.writeString(1, getSenderId());
      }
      if (locationLat_ != 0D) {
        output.writeDouble(2, locationLat_);
      }
      if (locationLng_ != 0D) {
        output.writeDouble(3, locationLng_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!senderId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSenderId());
      }
      if (locationLat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, locationLat_);
      }
      if (locationLng_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, locationLng_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static UpdateLocation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UpdateLocation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UpdateLocation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UpdateLocation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UpdateLocation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UpdateLocation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UpdateLocation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static UpdateLocation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UpdateLocation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UpdateLocation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UpdateLocation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.UpdateLocation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UpdateLocation, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.UpdateLocation)
        UpdateLocationOrBuilder {
      // Construct using com.brilltech.jelp.entities.EmergencyProto.UpdateLocation.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string senderId = 1;</code>
       */
      public String getSenderId() {
        return instance.getSenderId();
      }
      /**
       * <code>optional string senderId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        return instance.getSenderIdBytes();
      }
      /**
       * <code>optional string senderId = 1;</code>
       */
      public Builder setSenderId(
          String value) {
        copyOnWrite();
        instance.setSenderId(value);
        return this;
      }
      /**
       * <code>optional string senderId = 1;</code>
       */
      public Builder clearSenderId() {
        copyOnWrite();
        instance.clearSenderId();
        return this;
      }
      /**
       * <code>optional string senderId = 1;</code>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderIdBytes(value);
        return this;
      }

      /**
       * <code>optional double locationLat = 2;</code>
       */
      public double getLocationLat() {
        return instance.getLocationLat();
      }
      /**
       * <code>optional double locationLat = 2;</code>
       */
      public Builder setLocationLat(double value) {
        copyOnWrite();
        instance.setLocationLat(value);
        return this;
      }
      /**
       * <code>optional double locationLat = 2;</code>
       */
      public Builder clearLocationLat() {
        copyOnWrite();
        instance.clearLocationLat();
        return this;
      }

      /**
       * <code>optional double locationLng = 3;</code>
       */
      public double getLocationLng() {
        return instance.getLocationLng();
      }
      /**
       * <code>optional double locationLng = 3;</code>
       */
      public Builder setLocationLng(double value) {
        copyOnWrite();
        instance.setLocationLng(value);
        return this;
      }
      /**
       * <code>optional double locationLng = 3;</code>
       */
      public Builder clearLocationLng() {
        copyOnWrite();
        instance.clearLocationLng();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.UpdateLocation)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UpdateLocation();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          UpdateLocation other = (UpdateLocation) arg1;
          senderId_ = visitor.visitString(!senderId_.isEmpty(), senderId_,
              !other.senderId_.isEmpty(), other.senderId_);
          locationLat_ = visitor.visitDouble(locationLat_ != 0D, locationLat_,
              other.locationLat_ != 0D, other.locationLat_);
          locationLng_ = visitor.visitDouble(locationLng_ != 0D, locationLng_,
              other.locationLng_ != 0D, other.locationLng_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  senderId_ = s;
                  break;
                }
                case 17: {

                  locationLat_ = input.readDouble();
                  break;
                }
                case 25: {

                  locationLng_ = input.readDouble();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (UpdateLocation.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.UpdateLocation)
    private static final UpdateLocation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UpdateLocation();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static UpdateLocation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UpdateLocation> PARSER;

    public static com.google.protobuf.Parser<UpdateLocation> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
