// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package com.brilltech.jelp.entities;

public final class EventProto {
  private EventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code brilltech.jelp.entities.EventType}
   */
  public enum EventType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_EVENT_TYPE = 0;</code>
     */
    UNKNOWN_EVENT_TYPE(0),
    /**
     * <code>NOTIFICATION = 1;</code>
     */
    NOTIFICATION(1),
    /**
     * <code>NOTIFY = 2;</code>
     */
    NOTIFY(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_EVENT_TYPE = 0;</code>
     */
    public static final int UNKNOWN_EVENT_TYPE_VALUE = 0;
    /**
     * <code>NOTIFICATION = 1;</code>
     */
    public static final int NOTIFICATION_VALUE = 1;
    /**
     * <code>NOTIFY = 2;</code>
     */
    public static final int NOTIFY_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_EVENT_TYPE;
        case 1: return NOTIFICATION;
        case 2: return NOTIFY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brilltech.jelp.entities.EventType)
  }

  /**
   * Protobuf enum {@code brilltech.jelp.entities.NotificationType}
   */
  public enum NotificationType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_NOTIFICATION_TYPE = 0;</code>
     */
    UNKNOWN_NOTIFICATION_TYPE(0),
    /**
     * <code>PUSH = 1;</code>
     */
    PUSH(1),
    /**
     * <code>SMS = 2;</code>
     */
    SMS(2),
    /**
     * <code>EMAIL = 3;</code>
     */
    EMAIL(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_NOTIFICATION_TYPE = 0;</code>
     */
    public static final int UNKNOWN_NOTIFICATION_TYPE_VALUE = 0;
    /**
     * <code>PUSH = 1;</code>
     */
    public static final int PUSH_VALUE = 1;
    /**
     * <code>SMS = 2;</code>
     */
    public static final int SMS_VALUE = 2;
    /**
     * <code>EMAIL = 3;</code>
     */
    public static final int EMAIL_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static NotificationType valueOf(int value) {
      return forNumber(value);
    }

    public static NotificationType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_NOTIFICATION_TYPE;
        case 1: return PUSH;
        case 2: return SMS;
        case 3: return EMAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NotificationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NotificationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NotificationType>() {
            public NotificationType findValueByNumber(int number) {
              return NotificationType.forNumber(number);
            }
          };

    private final int value;

    private NotificationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brilltech.jelp.entities.NotificationType)
  }

  public interface NotificationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.NotificationData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string notificationId = 1;</code>
     */
    String getNotificationId();
    /**
     * <code>optional string notificationId = 1;</code>
     */
    com.google.protobuf.ByteString
        getNotificationIdBytes();

    /**
     * <code>optional string formattedMsg = 2;</code>
     */
    String getFormattedMsg();
    /**
     * <code>optional string formattedMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getFormattedMsgBytes();

    /**
     * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
     */
    int getNotificationTypeValue();
    /**
     * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
     */
    NotificationType getNotificationType();

    /**
     * <code>optional string emailSubject = 4;</code>
     */
    String getEmailSubject();
    /**
     * <code>optional string emailSubject = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailSubjectBytes();

    /**
     * <code>optional string emailBody = 5;</code>
     */
    String getEmailBody();
    /**
     * <code>optional string emailBody = 5;</code>
     */
    com.google.protobuf.ByteString
        getEmailBodyBytes();

    /**
     * <code>repeated string emailTos = 6;</code>
     */
    java.util.List<String>
        getEmailTosList();
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    int getEmailTosCount();
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    String getEmailTos(int index);
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    com.google.protobuf.ByteString
        getEmailTosBytes(int index);

    /**
     * <code>optional string emailFrom = 7;</code>
     */
    String getEmailFrom();
    /**
     * <code>optional string emailFrom = 7;</code>
     */
    com.google.protobuf.ByteString
        getEmailFromBytes();

    /**
     * <code>optional bool isEmailHtml = 8;</code>
     */
    boolean getIsEmailHtml();

    /**
     * <code>optional string senderUserId = 9;</code>
     */
    String getSenderUserId();
    /**
     * <code>optional string senderUserId = 9;</code>
     */
    com.google.protobuf.ByteString
        getSenderUserIdBytes();

    /**
     * <code>optional string senderSessionId = 10;</code>
     */
    String getSenderSessionId();
    /**
     * <code>optional string senderSessionId = 10;</code>
     */
    com.google.protobuf.ByteString
        getSenderSessionIdBytes();

    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    java.util.List<String>
        getReceiverUserIdsList();
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    int getReceiverUserIdsCount();
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    String getReceiverUserIds(int index);
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    com.google.protobuf.ByteString
        getReceiverUserIdsBytes(int index);

    /**
     * <code>optional string refId = 12;</code>
     */
    String getRefId();
    /**
     * <code>optional string refId = 12;</code>
     */
    com.google.protobuf.ByteString
        getRefIdBytes();

    /**
     * <code>optional bytes payload = 13;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>optional string title = 14;</code>
     */
    String getTitle();
    /**
     * <code>optional string title = 14;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string category = 15;</code>
     */
    String getCategory();
    /**
     * <code>optional string category = 15;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>optional bool silent = 16;</code>
     */
    boolean getSilent();

    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
     */
    int getDeviceTypeValue();
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
     */
    JelpProto.DeviceType getDeviceType();

    /**
     * <code>optional string pushToken = 18;</code>
     */
    String getPushToken();
    /**
     * <code>optional string pushToken = 18;</code>
     */
    com.google.protobuf.ByteString
        getPushTokenBytes();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.NotificationData}
   */
  public  static final class NotificationData extends
      com.google.protobuf.GeneratedMessageLite<
          NotificationData, NotificationData.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.NotificationData)
      NotificationDataOrBuilder {
    private NotificationData() {
      notificationId_ = "";
      formattedMsg_ = "";
      emailSubject_ = "";
      emailBody_ = "";
      emailTos_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      emailFrom_ = "";
      senderUserId_ = "";
      senderSessionId_ = "";
      receiverUserIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      refId_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
      title_ = "";
      category_ = "";
      pushToken_ = "";
    }
    private int bitField0_;
    public static final int NOTIFICATIONID_FIELD_NUMBER = 1;
    private String notificationId_;
    /**
     * <code>optional string notificationId = 1;</code>
     */
    public String getNotificationId() {
      return notificationId_;
    }
    /**
     * <code>optional string notificationId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNotificationIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(notificationId_);
    }
    /**
     * <code>optional string notificationId = 1;</code>
     */
    private void setNotificationId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      notificationId_ = value;
    }
    /**
     * <code>optional string notificationId = 1;</code>
     */
    private void clearNotificationId() {
      
      notificationId_ = getDefaultInstance().getNotificationId();
    }
    /**
     * <code>optional string notificationId = 1;</code>
     */
    private void setNotificationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      notificationId_ = value.toStringUtf8();
    }

    public static final int FORMATTEDMSG_FIELD_NUMBER = 2;
    private String formattedMsg_;
    /**
     * <code>optional string formattedMsg = 2;</code>
     */
    public String getFormattedMsg() {
      return formattedMsg_;
    }
    /**
     * <code>optional string formattedMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFormattedMsgBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(formattedMsg_);
    }
    /**
     * <code>optional string formattedMsg = 2;</code>
     */
    private void setFormattedMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      formattedMsg_ = value;
    }
    /**
     * <code>optional string formattedMsg = 2;</code>
     */
    private void clearFormattedMsg() {
      
      formattedMsg_ = getDefaultInstance().getFormattedMsg();
    }
    /**
     * <code>optional string formattedMsg = 2;</code>
     */
    private void setFormattedMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      formattedMsg_ = value.toStringUtf8();
    }

    public static final int NOTIFICATIONTYPE_FIELD_NUMBER = 3;
    private int notificationType_;
    /**
     * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
     */
    public int getNotificationTypeValue() {
      return notificationType_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
     */
    public NotificationType getNotificationType() {
      NotificationType result = NotificationType.forNumber(notificationType_);
      return result == null ? NotificationType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
     */
    private void setNotificationTypeValue(int value) {
        notificationType_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
     */
    private void setNotificationType(NotificationType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      notificationType_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
     */
    private void clearNotificationType() {
      
      notificationType_ = 0;
    }

    public static final int EMAILSUBJECT_FIELD_NUMBER = 4;
    private String emailSubject_;
    /**
     * <code>optional string emailSubject = 4;</code>
     */
    public String getEmailSubject() {
      return emailSubject_;
    }
    /**
     * <code>optional string emailSubject = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailSubjectBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emailSubject_);
    }
    /**
     * <code>optional string emailSubject = 4;</code>
     */
    private void setEmailSubject(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emailSubject_ = value;
    }
    /**
     * <code>optional string emailSubject = 4;</code>
     */
    private void clearEmailSubject() {
      
      emailSubject_ = getDefaultInstance().getEmailSubject();
    }
    /**
     * <code>optional string emailSubject = 4;</code>
     */
    private void setEmailSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emailSubject_ = value.toStringUtf8();
    }

    public static final int EMAILBODY_FIELD_NUMBER = 5;
    private String emailBody_;
    /**
     * <code>optional string emailBody = 5;</code>
     */
    public String getEmailBody() {
      return emailBody_;
    }
    /**
     * <code>optional string emailBody = 5;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBodyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emailBody_);
    }
    /**
     * <code>optional string emailBody = 5;</code>
     */
    private void setEmailBody(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emailBody_ = value;
    }
    /**
     * <code>optional string emailBody = 5;</code>
     */
    private void clearEmailBody() {
      
      emailBody_ = getDefaultInstance().getEmailBody();
    }
    /**
     * <code>optional string emailBody = 5;</code>
     */
    private void setEmailBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emailBody_ = value.toStringUtf8();
    }

    public static final int EMAILTOS_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.ProtobufList<String> emailTos_;
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    public java.util.List<String> getEmailTosList() {
      return emailTos_;
    }
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    public int getEmailTosCount() {
      return emailTos_.size();
    }
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    public String getEmailTos(int index) {
      return emailTos_.get(index);
    }
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    public com.google.protobuf.ByteString
        getEmailTosBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          emailTos_.get(index));
    }
    private void ensureEmailTosIsMutable() {
      if (!emailTos_.isModifiable()) {
        emailTos_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(emailTos_);
       }
    }
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    private void setEmailTos(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailTosIsMutable();
      emailTos_.set(index, value);
    }
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    private void addEmailTos(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailTosIsMutable();
      emailTos_.add(value);
    }
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    private void addAllEmailTos(
        Iterable<String> values) {
      ensureEmailTosIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, emailTos_);
    }
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    private void clearEmailTos() {
      emailTos_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string emailTos = 6;</code>
     */
    private void addEmailTosBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEmailTosIsMutable();
      emailTos_.add(value.toStringUtf8());
    }

    public static final int EMAILFROM_FIELD_NUMBER = 7;
    private String emailFrom_;
    /**
     * <code>optional string emailFrom = 7;</code>
     */
    public String getEmailFrom() {
      return emailFrom_;
    }
    /**
     * <code>optional string emailFrom = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEmailFromBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emailFrom_);
    }
    /**
     * <code>optional string emailFrom = 7;</code>
     */
    private void setEmailFrom(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emailFrom_ = value;
    }
    /**
     * <code>optional string emailFrom = 7;</code>
     */
    private void clearEmailFrom() {
      
      emailFrom_ = getDefaultInstance().getEmailFrom();
    }
    /**
     * <code>optional string emailFrom = 7;</code>
     */
    private void setEmailFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emailFrom_ = value.toStringUtf8();
    }

    public static final int ISEMAILHTML_FIELD_NUMBER = 8;
    private boolean isEmailHtml_;
    /**
     * <code>optional bool isEmailHtml = 8;</code>
     */
    public boolean getIsEmailHtml() {
      return isEmailHtml_;
    }
    /**
     * <code>optional bool isEmailHtml = 8;</code>
     */
    private void setIsEmailHtml(boolean value) {
      
      isEmailHtml_ = value;
    }
    /**
     * <code>optional bool isEmailHtml = 8;</code>
     */
    private void clearIsEmailHtml() {
      
      isEmailHtml_ = false;
    }

    public static final int SENDERUSERID_FIELD_NUMBER = 9;
    private String senderUserId_;
    /**
     * <code>optional string senderUserId = 9;</code>
     */
    public String getSenderUserId() {
      return senderUserId_;
    }
    /**
     * <code>optional string senderUserId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSenderUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(senderUserId_);
    }
    /**
     * <code>optional string senderUserId = 9;</code>
     */
    private void setSenderUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderUserId_ = value;
    }
    /**
     * <code>optional string senderUserId = 9;</code>
     */
    private void clearSenderUserId() {
      
      senderUserId_ = getDefaultInstance().getSenderUserId();
    }
    /**
     * <code>optional string senderUserId = 9;</code>
     */
    private void setSenderUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderUserId_ = value.toStringUtf8();
    }

    public static final int SENDERSESSIONID_FIELD_NUMBER = 10;
    private String senderSessionId_;
    /**
     * <code>optional string senderSessionId = 10;</code>
     */
    public String getSenderSessionId() {
      return senderSessionId_;
    }
    /**
     * <code>optional string senderSessionId = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSenderSessionIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(senderSessionId_);
    }
    /**
     * <code>optional string senderSessionId = 10;</code>
     */
    private void setSenderSessionId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderSessionId_ = value;
    }
    /**
     * <code>optional string senderSessionId = 10;</code>
     */
    private void clearSenderSessionId() {
      
      senderSessionId_ = getDefaultInstance().getSenderSessionId();
    }
    /**
     * <code>optional string senderSessionId = 10;</code>
     */
    private void setSenderSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderSessionId_ = value.toStringUtf8();
    }

    public static final int RECEIVERUSERIDS_FIELD_NUMBER = 11;
    private com.google.protobuf.Internal.ProtobufList<String> receiverUserIds_;
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    public java.util.List<String> getReceiverUserIdsList() {
      return receiverUserIds_;
    }
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    public int getReceiverUserIdsCount() {
      return receiverUserIds_.size();
    }
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    public String getReceiverUserIds(int index) {
      return receiverUserIds_.get(index);
    }
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverUserIdsBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          receiverUserIds_.get(index));
    }
    private void ensureReceiverUserIdsIsMutable() {
      if (!receiverUserIds_.isModifiable()) {
        receiverUserIds_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(receiverUserIds_);
       }
    }
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    private void setReceiverUserIds(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiverUserIdsIsMutable();
      receiverUserIds_.set(index, value);
    }
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    private void addReceiverUserIds(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReceiverUserIdsIsMutable();
      receiverUserIds_.add(value);
    }
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    private void addAllReceiverUserIds(
        Iterable<String> values) {
      ensureReceiverUserIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, receiverUserIds_);
    }
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    private void clearReceiverUserIds() {
      receiverUserIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string receiverUserIds = 11;</code>
     */
    private void addReceiverUserIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReceiverUserIdsIsMutable();
      receiverUserIds_.add(value.toStringUtf8());
    }

    public static final int REFID_FIELD_NUMBER = 12;
    private String refId_;
    /**
     * <code>optional string refId = 12;</code>
     */
    public String getRefId() {
      return refId_;
    }
    /**
     * <code>optional string refId = 12;</code>
     */
    public com.google.protobuf.ByteString
        getRefIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(refId_);
    }
    /**
     * <code>optional string refId = 12;</code>
     */
    private void setRefId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      refId_ = value;
    }
    /**
     * <code>optional string refId = 12;</code>
     */
    private void clearRefId() {
      
      refId_ = getDefaultInstance().getRefId();
    }
    /**
     * <code>optional string refId = 12;</code>
     */
    private void setRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      refId_ = value.toStringUtf8();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 13;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>optional bytes payload = 13;</code>
     */
    private void setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
    }
    /**
     * <code>optional bytes payload = 13;</code>
     */
    private void clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
    }

    public static final int TITLE_FIELD_NUMBER = 14;
    private String title_;
    /**
     * <code>optional string title = 14;</code>
     */
    public String getTitle() {
      return title_;
    }
    /**
     * <code>optional string title = 14;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(title_);
    }
    /**
     * <code>optional string title = 14;</code>
     */
    private void setTitle(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
    }
    /**
     * <code>optional string title = 14;</code>
     */
    private void clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
    }
    /**
     * <code>optional string title = 14;</code>
     */
    private void setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value.toStringUtf8();
    }

    public static final int CATEGORY_FIELD_NUMBER = 15;
    private String category_;
    /**
     * <code>optional string category = 15;</code>
     */
    public String getCategory() {
      return category_;
    }
    /**
     * <code>optional string category = 15;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(category_);
    }
    /**
     * <code>optional string category = 15;</code>
     */
    private void setCategory(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      category_ = value;
    }
    /**
     * <code>optional string category = 15;</code>
     */
    private void clearCategory() {
      
      category_ = getDefaultInstance().getCategory();
    }
    /**
     * <code>optional string category = 15;</code>
     */
    private void setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      category_ = value.toStringUtf8();
    }

    public static final int SILENT_FIELD_NUMBER = 16;
    private boolean silent_;
    /**
     * <code>optional bool silent = 16;</code>
     */
    public boolean getSilent() {
      return silent_;
    }
    /**
     * <code>optional bool silent = 16;</code>
     */
    private void setSilent(boolean value) {
      
      silent_ = value;
    }
    /**
     * <code>optional bool silent = 16;</code>
     */
    private void clearSilent() {
      
      silent_ = false;
    }

    public static final int DEVICETYPE_FIELD_NUMBER = 17;
    private int deviceType_;
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
     */
    public int getDeviceTypeValue() {
      return deviceType_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
     */
    public JelpProto.DeviceType getDeviceType() {
      JelpProto.DeviceType result = JelpProto.DeviceType.forNumber(deviceType_);
      return result == null ? JelpProto.DeviceType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
     */
    private void setDeviceTypeValue(int value) {
        deviceType_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
     */
    private void setDeviceType(JelpProto.DeviceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      deviceType_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
     */
    private void clearDeviceType() {
      
      deviceType_ = 0;
    }

    public static final int PUSHTOKEN_FIELD_NUMBER = 18;
    private String pushToken_;
    /**
     * <code>optional string pushToken = 18;</code>
     */
    public String getPushToken() {
      return pushToken_;
    }
    /**
     * <code>optional string pushToken = 18;</code>
     */
    public com.google.protobuf.ByteString
        getPushTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(pushToken_);
    }
    /**
     * <code>optional string pushToken = 18;</code>
     */
    private void setPushToken(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pushToken_ = value;
    }
    /**
     * <code>optional string pushToken = 18;</code>
     */
    private void clearPushToken() {
      
      pushToken_ = getDefaultInstance().getPushToken();
    }
    /**
     * <code>optional string pushToken = 18;</code>
     */
    private void setPushTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pushToken_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!notificationId_.isEmpty()) {
        output.writeString(1, getNotificationId());
      }
      if (!formattedMsg_.isEmpty()) {
        output.writeString(2, getFormattedMsg());
      }
      if (notificationType_ != NotificationType.UNKNOWN_NOTIFICATION_TYPE.getNumber()) {
        output.writeEnum(3, notificationType_);
      }
      if (!emailSubject_.isEmpty()) {
        output.writeString(4, getEmailSubject());
      }
      if (!emailBody_.isEmpty()) {
        output.writeString(5, getEmailBody());
      }
      for (int i = 0; i < emailTos_.size(); i++) {
        output.writeString(6, emailTos_.get(i));
      }
      if (!emailFrom_.isEmpty()) {
        output.writeString(7, getEmailFrom());
      }
      if (isEmailHtml_ != false) {
        output.writeBool(8, isEmailHtml_);
      }
      if (!senderUserId_.isEmpty()) {
        output.writeString(9, getSenderUserId());
      }
      if (!senderSessionId_.isEmpty()) {
        output.writeString(10, getSenderSessionId());
      }
      for (int i = 0; i < receiverUserIds_.size(); i++) {
        output.writeString(11, receiverUserIds_.get(i));
      }
      if (!refId_.isEmpty()) {
        output.writeString(12, getRefId());
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(13, payload_);
      }
      if (!title_.isEmpty()) {
        output.writeString(14, getTitle());
      }
      if (!category_.isEmpty()) {
        output.writeString(15, getCategory());
      }
      if (silent_ != false) {
        output.writeBool(16, silent_);
      }
      if (deviceType_ != JelpProto.DeviceType.UNKNOWN_DEVICE.getNumber()) {
        output.writeEnum(17, deviceType_);
      }
      if (!pushToken_.isEmpty()) {
        output.writeString(18, getPushToken());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!notificationId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getNotificationId());
      }
      if (!formattedMsg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getFormattedMsg());
      }
      if (notificationType_ != NotificationType.UNKNOWN_NOTIFICATION_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, notificationType_);
      }
      if (!emailSubject_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getEmailSubject());
      }
      if (!emailBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getEmailBody());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < emailTos_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(emailTos_.get(i));
        }
        size += dataSize;
        size += 1 * getEmailTosList().size();
      }
      if (!emailFrom_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getEmailFrom());
      }
      if (isEmailHtml_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isEmailHtml_);
      }
      if (!senderUserId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getSenderUserId());
      }
      if (!senderSessionId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getSenderSessionId());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < receiverUserIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(receiverUserIds_.get(i));
        }
        size += dataSize;
        size += 1 * getReceiverUserIdsList().size();
      }
      if (!refId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getRefId());
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, payload_);
      }
      if (!title_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getTitle());
      }
      if (!category_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(15, getCategory());
      }
      if (silent_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(16, silent_);
      }
      if (deviceType_ != JelpProto.DeviceType.UNKNOWN_DEVICE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(17, deviceType_);
      }
      if (!pushToken_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(18, getPushToken());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static NotificationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NotificationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NotificationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static NotificationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static NotificationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NotificationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NotificationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static NotificationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static NotificationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static NotificationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NotificationData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.NotificationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          NotificationData, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.NotificationData)
        NotificationDataOrBuilder {
      // Construct using com.brilltech.jelp.entities.EventProto.NotificationData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string notificationId = 1;</code>
       */
      public String getNotificationId() {
        return instance.getNotificationId();
      }
      /**
       * <code>optional string notificationId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNotificationIdBytes() {
        return instance.getNotificationIdBytes();
      }
      /**
       * <code>optional string notificationId = 1;</code>
       */
      public Builder setNotificationId(
          String value) {
        copyOnWrite();
        instance.setNotificationId(value);
        return this;
      }
      /**
       * <code>optional string notificationId = 1;</code>
       */
      public Builder clearNotificationId() {
        copyOnWrite();
        instance.clearNotificationId();
        return this;
      }
      /**
       * <code>optional string notificationId = 1;</code>
       */
      public Builder setNotificationIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNotificationIdBytes(value);
        return this;
      }

      /**
       * <code>optional string formattedMsg = 2;</code>
       */
      public String getFormattedMsg() {
        return instance.getFormattedMsg();
      }
      /**
       * <code>optional string formattedMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFormattedMsgBytes() {
        return instance.getFormattedMsgBytes();
      }
      /**
       * <code>optional string formattedMsg = 2;</code>
       */
      public Builder setFormattedMsg(
          String value) {
        copyOnWrite();
        instance.setFormattedMsg(value);
        return this;
      }
      /**
       * <code>optional string formattedMsg = 2;</code>
       */
      public Builder clearFormattedMsg() {
        copyOnWrite();
        instance.clearFormattedMsg();
        return this;
      }
      /**
       * <code>optional string formattedMsg = 2;</code>
       */
      public Builder setFormattedMsgBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFormattedMsgBytes(value);
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
       */
      public int getNotificationTypeValue() {
        return instance.getNotificationTypeValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
       */
      public Builder setNotificationTypeValue(int value) {
        copyOnWrite();
        instance.setNotificationTypeValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
       */
      public NotificationType getNotificationType() {
        return instance.getNotificationType();
      }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
       */
      public Builder setNotificationType(NotificationType value) {
        copyOnWrite();
        instance.setNotificationType(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationType notificationType = 3;</code>
       */
      public Builder clearNotificationType() {
        copyOnWrite();
        instance.clearNotificationType();
        return this;
      }

      /**
       * <code>optional string emailSubject = 4;</code>
       */
      public String getEmailSubject() {
        return instance.getEmailSubject();
      }
      /**
       * <code>optional string emailSubject = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailSubjectBytes() {
        return instance.getEmailSubjectBytes();
      }
      /**
       * <code>optional string emailSubject = 4;</code>
       */
      public Builder setEmailSubject(
          String value) {
        copyOnWrite();
        instance.setEmailSubject(value);
        return this;
      }
      /**
       * <code>optional string emailSubject = 4;</code>
       */
      public Builder clearEmailSubject() {
        copyOnWrite();
        instance.clearEmailSubject();
        return this;
      }
      /**
       * <code>optional string emailSubject = 4;</code>
       */
      public Builder setEmailSubjectBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailSubjectBytes(value);
        return this;
      }

      /**
       * <code>optional string emailBody = 5;</code>
       */
      public String getEmailBody() {
        return instance.getEmailBody();
      }
      /**
       * <code>optional string emailBody = 5;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBodyBytes() {
        return instance.getEmailBodyBytes();
      }
      /**
       * <code>optional string emailBody = 5;</code>
       */
      public Builder setEmailBody(
          String value) {
        copyOnWrite();
        instance.setEmailBody(value);
        return this;
      }
      /**
       * <code>optional string emailBody = 5;</code>
       */
      public Builder clearEmailBody() {
        copyOnWrite();
        instance.clearEmailBody();
        return this;
      }
      /**
       * <code>optional string emailBody = 5;</code>
       */
      public Builder setEmailBodyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBodyBytes(value);
        return this;
      }

      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public java.util.List<String>
          getEmailTosList() {
        return java.util.Collections.unmodifiableList(
            instance.getEmailTosList());
      }
      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public int getEmailTosCount() {
        return instance.getEmailTosCount();
      }
      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public String getEmailTos(int index) {
        return instance.getEmailTos(index);
      }
      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public com.google.protobuf.ByteString
          getEmailTosBytes(int index) {
        return instance.getEmailTosBytes(index);
      }
      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public Builder setEmailTos(
          int index, String value) {
        copyOnWrite();
        instance.setEmailTos(index, value);
        return this;
      }
      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public Builder addEmailTos(
          String value) {
        copyOnWrite();
        instance.addEmailTos(value);
        return this;
      }
      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public Builder addAllEmailTos(
          Iterable<String> values) {
        copyOnWrite();
        instance.addAllEmailTos(values);
        return this;
      }
      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public Builder clearEmailTos() {
        copyOnWrite();
        instance.clearEmailTos();
        return this;
      }
      /**
       * <code>repeated string emailTos = 6;</code>
       */
      public Builder addEmailTosBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addEmailTosBytes(value);
        return this;
      }

      /**
       * <code>optional string emailFrom = 7;</code>
       */
      public String getEmailFrom() {
        return instance.getEmailFrom();
      }
      /**
       * <code>optional string emailFrom = 7;</code>
       */
      public com.google.protobuf.ByteString
          getEmailFromBytes() {
        return instance.getEmailFromBytes();
      }
      /**
       * <code>optional string emailFrom = 7;</code>
       */
      public Builder setEmailFrom(
          String value) {
        copyOnWrite();
        instance.setEmailFrom(value);
        return this;
      }
      /**
       * <code>optional string emailFrom = 7;</code>
       */
      public Builder clearEmailFrom() {
        copyOnWrite();
        instance.clearEmailFrom();
        return this;
      }
      /**
       * <code>optional string emailFrom = 7;</code>
       */
      public Builder setEmailFromBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailFromBytes(value);
        return this;
      }

      /**
       * <code>optional bool isEmailHtml = 8;</code>
       */
      public boolean getIsEmailHtml() {
        return instance.getIsEmailHtml();
      }
      /**
       * <code>optional bool isEmailHtml = 8;</code>
       */
      public Builder setIsEmailHtml(boolean value) {
        copyOnWrite();
        instance.setIsEmailHtml(value);
        return this;
      }
      /**
       * <code>optional bool isEmailHtml = 8;</code>
       */
      public Builder clearIsEmailHtml() {
        copyOnWrite();
        instance.clearIsEmailHtml();
        return this;
      }

      /**
       * <code>optional string senderUserId = 9;</code>
       */
      public String getSenderUserId() {
        return instance.getSenderUserId();
      }
      /**
       * <code>optional string senderUserId = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSenderUserIdBytes() {
        return instance.getSenderUserIdBytes();
      }
      /**
       * <code>optional string senderUserId = 9;</code>
       */
      public Builder setSenderUserId(
          String value) {
        copyOnWrite();
        instance.setSenderUserId(value);
        return this;
      }
      /**
       * <code>optional string senderUserId = 9;</code>
       */
      public Builder clearSenderUserId() {
        copyOnWrite();
        instance.clearSenderUserId();
        return this;
      }
      /**
       * <code>optional string senderUserId = 9;</code>
       */
      public Builder setSenderUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderUserIdBytes(value);
        return this;
      }

      /**
       * <code>optional string senderSessionId = 10;</code>
       */
      public String getSenderSessionId() {
        return instance.getSenderSessionId();
      }
      /**
       * <code>optional string senderSessionId = 10;</code>
       */
      public com.google.protobuf.ByteString
          getSenderSessionIdBytes() {
        return instance.getSenderSessionIdBytes();
      }
      /**
       * <code>optional string senderSessionId = 10;</code>
       */
      public Builder setSenderSessionId(
          String value) {
        copyOnWrite();
        instance.setSenderSessionId(value);
        return this;
      }
      /**
       * <code>optional string senderSessionId = 10;</code>
       */
      public Builder clearSenderSessionId() {
        copyOnWrite();
        instance.clearSenderSessionId();
        return this;
      }
      /**
       * <code>optional string senderSessionId = 10;</code>
       */
      public Builder setSenderSessionIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderSessionIdBytes(value);
        return this;
      }

      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public java.util.List<String>
          getReceiverUserIdsList() {
        return java.util.Collections.unmodifiableList(
            instance.getReceiverUserIdsList());
      }
      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public int getReceiverUserIdsCount() {
        return instance.getReceiverUserIdsCount();
      }
      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public String getReceiverUserIds(int index) {
        return instance.getReceiverUserIds(index);
      }
      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverUserIdsBytes(int index) {
        return instance.getReceiverUserIdsBytes(index);
      }
      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public Builder setReceiverUserIds(
          int index, String value) {
        copyOnWrite();
        instance.setReceiverUserIds(index, value);
        return this;
      }
      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public Builder addReceiverUserIds(
          String value) {
        copyOnWrite();
        instance.addReceiverUserIds(value);
        return this;
      }
      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public Builder addAllReceiverUserIds(
          Iterable<String> values) {
        copyOnWrite();
        instance.addAllReceiverUserIds(values);
        return this;
      }
      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public Builder clearReceiverUserIds() {
        copyOnWrite();
        instance.clearReceiverUserIds();
        return this;
      }
      /**
       * <code>repeated string receiverUserIds = 11;</code>
       */
      public Builder addReceiverUserIdsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addReceiverUserIdsBytes(value);
        return this;
      }

      /**
       * <code>optional string refId = 12;</code>
       */
      public String getRefId() {
        return instance.getRefId();
      }
      /**
       * <code>optional string refId = 12;</code>
       */
      public com.google.protobuf.ByteString
          getRefIdBytes() {
        return instance.getRefIdBytes();
      }
      /**
       * <code>optional string refId = 12;</code>
       */
      public Builder setRefId(
          String value) {
        copyOnWrite();
        instance.setRefId(value);
        return this;
      }
      /**
       * <code>optional string refId = 12;</code>
       */
      public Builder clearRefId() {
        copyOnWrite();
        instance.clearRefId();
        return this;
      }
      /**
       * <code>optional string refId = 12;</code>
       */
      public Builder setRefIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRefIdBytes(value);
        return this;
      }

      /**
       * <code>optional bytes payload = 13;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return instance.getPayload();
      }
      /**
       * <code>optional bytes payload = 13;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPayload(value);
        return this;
      }
      /**
       * <code>optional bytes payload = 13;</code>
       */
      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }

      /**
       * <code>optional string title = 14;</code>
       */
      public String getTitle() {
        return instance.getTitle();
      }
      /**
       * <code>optional string title = 14;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return instance.getTitleBytes();
      }
      /**
       * <code>optional string title = 14;</code>
       */
      public Builder setTitle(
          String value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <code>optional string title = 14;</code>
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }
      /**
       * <code>optional string title = 14;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitleBytes(value);
        return this;
      }

      /**
       * <code>optional string category = 15;</code>
       */
      public String getCategory() {
        return instance.getCategory();
      }
      /**
       * <code>optional string category = 15;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        return instance.getCategoryBytes();
      }
      /**
       * <code>optional string category = 15;</code>
       */
      public Builder setCategory(
          String value) {
        copyOnWrite();
        instance.setCategory(value);
        return this;
      }
      /**
       * <code>optional string category = 15;</code>
       */
      public Builder clearCategory() {
        copyOnWrite();
        instance.clearCategory();
        return this;
      }
      /**
       * <code>optional string category = 15;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCategoryBytes(value);
        return this;
      }

      /**
       * <code>optional bool silent = 16;</code>
       */
      public boolean getSilent() {
        return instance.getSilent();
      }
      /**
       * <code>optional bool silent = 16;</code>
       */
      public Builder setSilent(boolean value) {
        copyOnWrite();
        instance.setSilent(value);
        return this;
      }
      /**
       * <code>optional bool silent = 16;</code>
       */
      public Builder clearSilent() {
        copyOnWrite();
        instance.clearSilent();
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
       */
      public int getDeviceTypeValue() {
        return instance.getDeviceTypeValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
       */
      public Builder setDeviceTypeValue(int value) {
        copyOnWrite();
        instance.setDeviceTypeValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
       */
      public JelpProto.DeviceType getDeviceType() {
        return instance.getDeviceType();
      }
      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
       */
      public Builder setDeviceType(JelpProto.DeviceType value) {
        copyOnWrite();
        instance.setDeviceType(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.DeviceType deviceType = 17;</code>
       */
      public Builder clearDeviceType() {
        copyOnWrite();
        instance.clearDeviceType();
        return this;
      }

      /**
       * <code>optional string pushToken = 18;</code>
       */
      public String getPushToken() {
        return instance.getPushToken();
      }
      /**
       * <code>optional string pushToken = 18;</code>
       */
      public com.google.protobuf.ByteString
          getPushTokenBytes() {
        return instance.getPushTokenBytes();
      }
      /**
       * <code>optional string pushToken = 18;</code>
       */
      public Builder setPushToken(
          String value) {
        copyOnWrite();
        instance.setPushToken(value);
        return this;
      }
      /**
       * <code>optional string pushToken = 18;</code>
       */
      public Builder clearPushToken() {
        copyOnWrite();
        instance.clearPushToken();
        return this;
      }
      /**
       * <code>optional string pushToken = 18;</code>
       */
      public Builder setPushTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPushTokenBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.NotificationData)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new NotificationData();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          emailTos_.makeImmutable();
          receiverUserIds_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          NotificationData other = (NotificationData) arg1;
          notificationId_ = visitor.visitString(!notificationId_.isEmpty(), notificationId_,
              !other.notificationId_.isEmpty(), other.notificationId_);
          formattedMsg_ = visitor.visitString(!formattedMsg_.isEmpty(), formattedMsg_,
              !other.formattedMsg_.isEmpty(), other.formattedMsg_);
          notificationType_ = visitor.visitInt(notificationType_ != 0, notificationType_,    other.notificationType_ != 0, other.notificationType_);
          emailSubject_ = visitor.visitString(!emailSubject_.isEmpty(), emailSubject_,
              !other.emailSubject_.isEmpty(), other.emailSubject_);
          emailBody_ = visitor.visitString(!emailBody_.isEmpty(), emailBody_,
              !other.emailBody_.isEmpty(), other.emailBody_);
          emailTos_= visitor.visitList(emailTos_, other.emailTos_);
          emailFrom_ = visitor.visitString(!emailFrom_.isEmpty(), emailFrom_,
              !other.emailFrom_.isEmpty(), other.emailFrom_);
          isEmailHtml_ = visitor.visitBoolean(isEmailHtml_ != false, isEmailHtml_,
              other.isEmailHtml_ != false, other.isEmailHtml_);
          senderUserId_ = visitor.visitString(!senderUserId_.isEmpty(), senderUserId_,
              !other.senderUserId_.isEmpty(), other.senderUserId_);
          senderSessionId_ = visitor.visitString(!senderSessionId_.isEmpty(), senderSessionId_,
              !other.senderSessionId_.isEmpty(), other.senderSessionId_);
          receiverUserIds_= visitor.visitList(receiverUserIds_, other.receiverUserIds_);
          refId_ = visitor.visitString(!refId_.isEmpty(), refId_,
              !other.refId_.isEmpty(), other.refId_);
          payload_ = visitor.visitByteString(payload_ != com.google.protobuf.ByteString.EMPTY, payload_,
              other.payload_ != com.google.protobuf.ByteString.EMPTY, other.payload_);
          title_ = visitor.visitString(!title_.isEmpty(), title_,
              !other.title_.isEmpty(), other.title_);
          category_ = visitor.visitString(!category_.isEmpty(), category_,
              !other.category_.isEmpty(), other.category_);
          silent_ = visitor.visitBoolean(silent_ != false, silent_,
              other.silent_ != false, other.silent_);
          deviceType_ = visitor.visitInt(deviceType_ != 0, deviceType_,    other.deviceType_ != 0, other.deviceType_);
          pushToken_ = visitor.visitString(!pushToken_.isEmpty(), pushToken_,
              !other.pushToken_.isEmpty(), other.pushToken_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  notificationId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  formattedMsg_ = s;
                  break;
                }
                case 24: {
                  int rawValue = input.readEnum();

                  notificationType_ = rawValue;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  emailSubject_ = s;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  emailBody_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();
                  if (!emailTos_.isModifiable()) {
                    emailTos_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(emailTos_);
                  }
                  emailTos_.add(s);
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();

                  emailFrom_ = s;
                  break;
                }
                case 64: {

                  isEmailHtml_ = input.readBool();
                  break;
                }
                case 74: {
                  String s = input.readStringRequireUtf8();

                  senderUserId_ = s;
                  break;
                }
                case 82: {
                  String s = input.readStringRequireUtf8();

                  senderSessionId_ = s;
                  break;
                }
                case 90: {
                  String s = input.readStringRequireUtf8();
                  if (!receiverUserIds_.isModifiable()) {
                    receiverUserIds_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(receiverUserIds_);
                  }
                  receiverUserIds_.add(s);
                  break;
                }
                case 98: {
                  String s = input.readStringRequireUtf8();

                  refId_ = s;
                  break;
                }
                case 106: {

                  payload_ = input.readBytes();
                  break;
                }
                case 114: {
                  String s = input.readStringRequireUtf8();

                  title_ = s;
                  break;
                }
                case 122: {
                  String s = input.readStringRequireUtf8();

                  category_ = s;
                  break;
                }
                case 128: {

                  silent_ = input.readBool();
                  break;
                }
                case 136: {
                  int rawValue = input.readEnum();

                  deviceType_ = rawValue;
                  break;
                }
                case 146: {
                  String s = input.readStringRequireUtf8();

                  pushToken_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (NotificationData.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.NotificationData)
    private static final NotificationData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NotificationData();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static NotificationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NotificationData> PARSER;

    public static com.google.protobuf.Parser<NotificationData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.Event)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string eventId = 1;</code>
     */
    String getEventId();
    /**
     * <code>optional string eventId = 1;</code>
     */
    com.google.protobuf.ByteString
        getEventIdBytes();

    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
     */
    int getEventTypeValue();
    /**
     * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
     */
    EventType getEventType();

    /**
     * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
     */
    boolean hasNotificationData();
    /**
     * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
     */
    NotificationData getNotificationData();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageLite<
          Event, Event.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.Event)
      EventOrBuilder {
    private Event() {
      eventId_ = "";
    }
    public static final int EVENTID_FIELD_NUMBER = 1;
    private String eventId_;
    /**
     * <code>optional string eventId = 1;</code>
     */
    public String getEventId() {
      return eventId_;
    }
    /**
     * <code>optional string eventId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(eventId_);
    }
    /**
     * <code>optional string eventId = 1;</code>
     */
    private void setEventId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventId_ = value;
    }
    /**
     * <code>optional string eventId = 1;</code>
     */
    private void clearEventId() {
      
      eventId_ = getDefaultInstance().getEventId();
    }
    /**
     * <code>optional string eventId = 1;</code>
     */
    private void setEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventId_ = value.toStringUtf8();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = 0L;
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 3;
    private int eventType_;
    /**
     * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
     */
    public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
     */
    public EventType getEventType() {
      EventType result = EventType.forNumber(eventType_);
      return result == null ? EventType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
     */
    private void setEventTypeValue(int value) {
        eventType_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
     */
    private void setEventType(EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      eventType_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
     */
    private void clearEventType() {
      
      eventType_ = 0;
    }

    public static final int NOTIFICATIONDATA_FIELD_NUMBER = 4;
    private NotificationData notificationData_;
    /**
     * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
     */
    public boolean hasNotificationData() {
      return notificationData_ != null;
    }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
     */
    public NotificationData getNotificationData() {
      return notificationData_ == null ? NotificationData.getDefaultInstance() : notificationData_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
     */
    private void setNotificationData(NotificationData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      notificationData_ = value;
      
      }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
     */
    private void setNotificationData(
        NotificationData.Builder builderForValue) {
      notificationData_ = builderForValue.build();
      
    }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
     */
    private void mergeNotificationData(NotificationData value) {
      if (notificationData_ != null &&
          notificationData_ != NotificationData.getDefaultInstance()) {
        notificationData_ =
          NotificationData.newBuilder(notificationData_).mergeFrom(value).buildPartial();
      } else {
        notificationData_ = value;
      }
      
    }
    /**
     * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
     */
    private void clearNotificationData() {  notificationData_ = null;
      
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!eventId_.isEmpty()) {
        output.writeString(1, getEventId());
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (eventType_ != EventType.UNKNOWN_EVENT_TYPE.getNumber()) {
        output.writeEnum(3, eventType_);
      }
      if (notificationData_ != null) {
        output.writeMessage(4, getNotificationData());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!eventId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getEventId());
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (eventType_ != EventType.UNKNOWN_EVENT_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, eventType_);
      }
      if (notificationData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getNotificationData());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Event, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.Event)
        EventOrBuilder {
      // Construct using com.brilltech.jelp.entities.EventProto.Event.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string eventId = 1;</code>
       */
      public String getEventId() {
        return instance.getEventId();
      }
      /**
       * <code>optional string eventId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEventIdBytes() {
        return instance.getEventIdBytes();
      }
      /**
       * <code>optional string eventId = 1;</code>
       */
      public Builder setEventId(
          String value) {
        copyOnWrite();
        instance.setEventId(value);
        return this;
      }
      /**
       * <code>optional string eventId = 1;</code>
       */
      public Builder clearEventId() {
        copyOnWrite();
        instance.clearEventId();
        return this;
      }
      /**
       * <code>optional string eventId = 1;</code>
       */
      public Builder setEventIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEventIdBytes(value);
        return this;
      }

      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
       */
      public int getEventTypeValue() {
        return instance.getEventTypeValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
       */
      public Builder setEventTypeValue(int value) {
        copyOnWrite();
        instance.setEventTypeValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
       */
      public EventType getEventType() {
        return instance.getEventType();
      }
      /**
       * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
       */
      public Builder setEventType(EventType value) {
        copyOnWrite();
        instance.setEventType(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.EventType eventType = 3;</code>
       */
      public Builder clearEventType() {
        copyOnWrite();
        instance.clearEventType();
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
       */
      public boolean hasNotificationData() {
        return instance.hasNotificationData();
      }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
       */
      public NotificationData getNotificationData() {
        return instance.getNotificationData();
      }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
       */
      public Builder setNotificationData(NotificationData value) {
        copyOnWrite();
        instance.setNotificationData(value);
        return this;
        }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
       */
      public Builder setNotificationData(
          NotificationData.Builder builderForValue) {
        copyOnWrite();
        instance.setNotificationData(builderForValue);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
       */
      public Builder mergeNotificationData(NotificationData value) {
        copyOnWrite();
        instance.mergeNotificationData(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.NotificationData notificationData = 4;</code>
       */
      public Builder clearNotificationData() {  copyOnWrite();
        instance.clearNotificationData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.Event)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Event();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          Event other = (Event) arg1;
          eventId_ = visitor.visitString(!eventId_.isEmpty(), eventId_,
              !other.eventId_.isEmpty(), other.eventId_);
          timestamp_ = visitor.visitLong(timestamp_ != 0L, timestamp_,
              other.timestamp_ != 0L, other.timestamp_);
          eventType_ = visitor.visitInt(eventType_ != 0, eventType_,    other.eventType_ != 0, other.eventType_);
          notificationData_ = visitor.visitMessage(notificationData_, other.notificationData_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  eventId_ = s;
                  break;
                }
                case 16: {

                  timestamp_ = input.readInt64();
                  break;
                }
                case 24: {
                  int rawValue = input.readEnum();

                  eventType_ = rawValue;
                  break;
                }
                case 34: {
                  NotificationData.Builder subBuilder = null;
                  if (notificationData_ != null) {
                    subBuilder = notificationData_.toBuilder();
                  }
                  notificationData_ = input.readMessage(NotificationData.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(notificationData_);
                    notificationData_ = subBuilder.buildPartial();
                  }

                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (Event.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.Event)
    private static final Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Event();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Event> PARSER;

    public static com.google.protobuf.Parser<Event> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
