// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jelp.proto

package com.brilltech.jelp.entities;

public final class JelpProto {
  private JelpProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code brilltech.jelp.entities.UserType}
   */
  public enum UserType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_USER_TYPE = 0;</code>
     */
    UNKNOWN_USER_TYPE(0),
    /**
     * <code>ADMIN = 1;</code>
     */
    ADMIN(1),
    /**
     * <code>CONSUMER = 2;</code>
     */
    CONSUMER(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_USER_TYPE = 0;</code>
     */
    public static final int UNKNOWN_USER_TYPE_VALUE = 0;
    /**
     * <code>ADMIN = 1;</code>
     */
    public static final int ADMIN_VALUE = 1;
    /**
     * <code>CONSUMER = 2;</code>
     */
    public static final int CONSUMER_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static UserType valueOf(int value) {
      return forNumber(value);
    }

    public static UserType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_USER_TYPE;
        case 1: return ADMIN;
        case 2: return CONSUMER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.forNumber(number);
            }
          };

    private final int value;

    private UserType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brilltech.jelp.entities.UserType)
  }

  /**
   * Protobuf enum {@code brilltech.jelp.entities.DeviceType}
   */
  public enum DeviceType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_DEVICE = 0;</code>
     */
    UNKNOWN_DEVICE(0),
    /**
     * <code>ANDROID = 2;</code>
     */
    ANDROID(2),
    /**
     * <code>IOS = 3;</code>
     */
    IOS(3),
    /**
     * <pre>
     *Effect, Action, Condition
     * </pre>
     *
     * <code>WEB = 4;</code>
     */
    WEB(4),
    /**
     * <code>IOS_WEB = 5;</code>
     */
    IOS_WEB(5),
    /**
     * <code>ANDROID_WEB = 6;</code>
     */
    ANDROID_WEB(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_DEVICE = 0;</code>
     */
    public static final int UNKNOWN_DEVICE_VALUE = 0;
    /**
     * <code>ANDROID = 2;</code>
     */
    public static final int ANDROID_VALUE = 2;
    /**
     * <code>IOS = 3;</code>
     */
    public static final int IOS_VALUE = 3;
    /**
     * <pre>
     *Effect, Action, Condition
     * </pre>
     *
     * <code>WEB = 4;</code>
     */
    public static final int WEB_VALUE = 4;
    /**
     * <code>IOS_WEB = 5;</code>
     */
    public static final int IOS_WEB_VALUE = 5;
    /**
     * <code>ANDROID_WEB = 6;</code>
     */
    public static final int ANDROID_WEB_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DeviceType valueOf(int value) {
      return forNumber(value);
    }

    public static DeviceType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_DEVICE;
        case 2: return ANDROID;
        case 3: return IOS;
        case 4: return WEB;
        case 5: return IOS_WEB;
        case 6: return ANDROID_WEB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DeviceType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
            public DeviceType findValueByNumber(int number) {
              return DeviceType.forNumber(number);
            }
          };

    private final int value;

    private DeviceType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brilltech.jelp.entities.DeviceType)
  }

  /**
   * Protobuf enum {@code brilltech.jelp.entities.UserStatus}
   */
  public enum UserStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_USER_STATUS = 0;</code>
     */
    UNKNOWN_USER_STATUS(0),
    /**
     * <code>ACCOUNT_VERIFICATION_PENDING = 1;</code>
     */
    ACCOUNT_VERIFICATION_PENDING(1),
    /**
     * <code>ACCOUNT_VERIFIED = 2;</code>
     */
    ACCOUNT_VERIFIED(2),
    /**
     * <code>ACCOUNT_DISABLED = 3;</code>
     */
    ACCOUNT_DISABLED(3),
    /**
     * <code>ACCOUNT_SUSPENDED = 4;</code>
     */
    ACCOUNT_SUSPENDED(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_USER_STATUS = 0;</code>
     */
    public static final int UNKNOWN_USER_STATUS_VALUE = 0;
    /**
     * <code>ACCOUNT_VERIFICATION_PENDING = 1;</code>
     */
    public static final int ACCOUNT_VERIFICATION_PENDING_VALUE = 1;
    /**
     * <code>ACCOUNT_VERIFIED = 2;</code>
     */
    public static final int ACCOUNT_VERIFIED_VALUE = 2;
    /**
     * <code>ACCOUNT_DISABLED = 3;</code>
     */
    public static final int ACCOUNT_DISABLED_VALUE = 3;
    /**
     * <code>ACCOUNT_SUSPENDED = 4;</code>
     */
    public static final int ACCOUNT_SUSPENDED_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static UserStatus valueOf(int value) {
      return forNumber(value);
    }

    public static UserStatus forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_USER_STATUS;
        case 1: return ACCOUNT_VERIFICATION_PENDING;
        case 2: return ACCOUNT_VERIFIED;
        case 3: return ACCOUNT_DISABLED;
        case 4: return ACCOUNT_SUSPENDED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserStatus>() {
            public UserStatus findValueByNumber(int number) {
              return UserStatus.forNumber(number);
            }
          };

    private final int value;

    private UserStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brilltech.jelp.entities.UserStatus)
  }

  /**
   * Protobuf enum {@code brilltech.jelp.entities.Gender}
   */
  public enum Gender
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_GENDER = 0;</code>
     */
    UNKNOWN_GENDER(0),
    /**
     * <code>MALE = 1;</code>
     */
    MALE(1),
    /**
     * <code>FEMALE = 2;</code>
     */
    FEMALE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_GENDER = 0;</code>
     */
    public static final int UNKNOWN_GENDER_VALUE = 0;
    /**
     * <code>MALE = 1;</code>
     */
    public static final int MALE_VALUE = 1;
    /**
     * <code>FEMALE = 2;</code>
     */
    public static final int FEMALE_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_GENDER;
        case 1: return MALE;
        case 2: return FEMALE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brilltech.jelp.entities.Gender)
  }

  /**
   * Protobuf enum {@code brilltech.jelp.entities.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_REQUEST_TYPE = 0;</code>
     */
    UNKNOWN_REQUEST_TYPE(0),
    /**
     * <code>ASSAULT = 1;</code>
     */
    ASSAULT(1),
    /**
     * <code>MEDICAL = 2;</code>
     */
    MEDICAL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_REQUEST_TYPE = 0;</code>
     */
    public static final int UNKNOWN_REQUEST_TYPE_VALUE = 0;
    /**
     * <code>ASSAULT = 1;</code>
     */
    public static final int ASSAULT_VALUE = 1;
    /**
     * <code>MEDICAL = 2;</code>
     */
    public static final int MEDICAL_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_REQUEST_TYPE;
        case 1: return ASSAULT;
        case 2: return MEDICAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brilltech.jelp.entities.RequestType)
  }

  /**
   * Protobuf enum {@code brilltech.jelp.entities.ResponseType}
   */
  public enum ResponseType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN_RESPONSE_TYPE = 0;</code>
     */
    UNKNOWN_RESPONSE_TYPE(0),
    /**
     * <code>ACCEPTED = 1;</code>
     */
    ACCEPTED(1),
    /**
     * <code>DECLINED = 2;</code>
     */
    DECLINED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_RESPONSE_TYPE = 0;</code>
     */
    public static final int UNKNOWN_RESPONSE_TYPE_VALUE = 0;
    /**
     * <code>ACCEPTED = 1;</code>
     */
    public static final int ACCEPTED_VALUE = 1;
    /**
     * <code>DECLINED = 2;</code>
     */
    public static final int DECLINED_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ResponseType valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_RESPONSE_TYPE;
        case 1: return ACCEPTED;
        case 2: return DECLINED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
            public ResponseType findValueByNumber(int number) {
              return ResponseType.forNumber(number);
            }
          };

    private final int value;

    private ResponseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:brilltech.jelp.entities.ResponseType)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
