// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: treeleaf.proto

package com.brilltech.jelp.entities;

public final class TreeleafProto {
    private TreeleafProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface DebugOrBuilder extends
            // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.Debug)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>optional string debugId = 1;</code>
         */
        String getDebugId();

        /**
         * <code>optional string debugId = 1;</code>
         */
        com.google.protobuf.ByteString
        getDebugIdBytes();

        /**
         * <code>optional string userId = 2;</code>
         */
        String getUserId();

        /**
         * <code>optional string userId = 2;</code>
         */
        com.google.protobuf.ByteString
        getUserIdBytes();

        /**
         * <pre>
         * Can be user agent or device id
         * </pre>
         *
         * <code>optional string client = 3;</code>
         */
        String getClient();

        /**
         * <pre>
         * Can be user agent or device id
         * </pre>
         *
         * <code>optional string client = 3;</code>
         */
        com.google.protobuf.ByteString
        getClientBytes();

        /**
         * <code>optional string locale = 4;</code>
         */
        String getLocale();

        /**
         * <code>optional string locale = 4;</code>
         */
        com.google.protobuf.ByteString
        getLocaleBytes();

        /**
         * <code>optional string traceId = 5;</code>
         */
        String getTraceId();

        /**
         * <code>optional string traceId = 5;</code>
         */
        com.google.protobuf.ByteString
        getTraceIdBytes();
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.Debug}
     */
    public static final class Debug extends
            com.google.protobuf.GeneratedMessageLite<
                    Debug, Debug.Builder> implements
            // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.Debug)
            DebugOrBuilder {
        private Debug() {
            debugId_ = "";
            userId_ = "";
            client_ = "";
            locale_ = "";
            traceId_ = "";
        }

        public static final int DEBUGID_FIELD_NUMBER = 1;
        private String debugId_;

        /**
         * <code>optional string debugId = 1;</code>
         */
        public String getDebugId() {
            return debugId_;
        }

        /**
         * <code>optional string debugId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getDebugIdBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(debugId_);
        }

        /**
         * <code>optional string debugId = 1;</code>
         */
        private void setDebugId(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            debugId_ = value;
        }

        /**
         * <code>optional string debugId = 1;</code>
         */
        private void clearDebugId() {

            debugId_ = getDefaultInstance().getDebugId();
        }

        /**
         * <code>optional string debugId = 1;</code>
         */
        private void setDebugIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            debugId_ = value.toStringUtf8();
        }

        public static final int USERID_FIELD_NUMBER = 2;
        private String userId_;

        /**
         * <code>optional string userId = 2;</code>
         */
        public String getUserId() {
            return userId_;
        }

        /**
         * <code>optional string userId = 2;</code>
         */
        public com.google.protobuf.ByteString
        getUserIdBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(userId_);
        }

        /**
         * <code>optional string userId = 2;</code>
         */
        private void setUserId(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            userId_ = value;
        }

        /**
         * <code>optional string userId = 2;</code>
         */
        private void clearUserId() {

            userId_ = getDefaultInstance().getUserId();
        }

        /**
         * <code>optional string userId = 2;</code>
         */
        private void setUserIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            userId_ = value.toStringUtf8();
        }

        public static final int CLIENT_FIELD_NUMBER = 3;
        private String client_;

        /**
         * <pre>
         * Can be user agent or device id
         * </pre>
         *
         * <code>optional string client = 3;</code>
         */
        public String getClient() {
            return client_;
        }

        /**
         * <pre>
         * Can be user agent or device id
         * </pre>
         *
         * <code>optional string client = 3;</code>
         */
        public com.google.protobuf.ByteString
        getClientBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(client_);
        }

        /**
         * <pre>
         * Can be user agent or device id
         * </pre>
         *
         * <code>optional string client = 3;</code>
         */
        private void setClient(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            client_ = value;
        }

        /**
         * <pre>
         * Can be user agent or device id
         * </pre>
         *
         * <code>optional string client = 3;</code>
         */
        private void clearClient() {

            client_ = getDefaultInstance().getClient();
        }

        /**
         * <pre>
         * Can be user agent or device id
         * </pre>
         *
         * <code>optional string client = 3;</code>
         */
        private void setClientBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            client_ = value.toStringUtf8();
        }

        public static final int LOCALE_FIELD_NUMBER = 4;
        private String locale_;

        /**
         * <code>optional string locale = 4;</code>
         */
        public String getLocale() {
            return locale_;
        }

        /**
         * <code>optional string locale = 4;</code>
         */
        public com.google.protobuf.ByteString
        getLocaleBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(locale_);
        }

        /**
         * <code>optional string locale = 4;</code>
         */
        private void setLocale(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            locale_ = value;
        }

        /**
         * <code>optional string locale = 4;</code>
         */
        private void clearLocale() {

            locale_ = getDefaultInstance().getLocale();
        }

        /**
         * <code>optional string locale = 4;</code>
         */
        private void setLocaleBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            locale_ = value.toStringUtf8();
        }

        public static final int TRACEID_FIELD_NUMBER = 5;
        private String traceId_;

        /**
         * <code>optional string traceId = 5;</code>
         */
        public String getTraceId() {
            return traceId_;
        }

        /**
         * <code>optional string traceId = 5;</code>
         */
        public com.google.protobuf.ByteString
        getTraceIdBytes() {
            return com.google.protobuf.ByteString.copyFromUtf8(traceId_);
        }

        /**
         * <code>optional string traceId = 5;</code>
         */
        private void setTraceId(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            traceId_ = value;
        }

        /**
         * <code>optional string traceId = 5;</code>
         */
        private void clearTraceId() {

            traceId_ = getDefaultInstance().getTraceId();
        }

        /**
         * <code>optional string traceId = 5;</code>
         */
        private void setTraceIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            traceId_ = value.toStringUtf8();
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!debugId_.isEmpty()) {
                output.writeString(1, getDebugId());
            }
            if (!userId_.isEmpty()) {
                output.writeString(2, getUserId());
            }
            if (!client_.isEmpty()) {
                output.writeString(3, getClient());
            }
            if (!locale_.isEmpty()) {
                output.writeString(4, getLocale());
            }
            if (!traceId_.isEmpty()) {
                output.writeString(5, getTraceId());
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (!debugId_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(1, getDebugId());
            }
            if (!userId_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(2, getUserId());
            }
            if (!client_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(3, getClient());
            }
            if (!locale_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(4, getLocale());
            }
            if (!traceId_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeStringSize(5, getTraceId());
            }
            memoizedSerializedSize = size;
            return size;
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.brilltech.jelp.entities.TreeleafProto.Debug prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        /**
         * Protobuf type {@code brilltech.jelp.entities.Debug}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        com.brilltech.jelp.entities.TreeleafProto.Debug, Builder> implements
                // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.Debug)
                com.brilltech.jelp.entities.TreeleafProto.DebugOrBuilder {
            // Construct using com.brilltech.jelp.entities.TreeleafProto.Debug.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>optional string debugId = 1;</code>
             */
            public String getDebugId() {
                return instance.getDebugId();
            }

            /**
             * <code>optional string debugId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getDebugIdBytes() {
                return instance.getDebugIdBytes();
            }

            /**
             * <code>optional string debugId = 1;</code>
             */
            public Builder setDebugId(
                    String value) {
                copyOnWrite();
                instance.setDebugId(value);
                return this;
            }

            /**
             * <code>optional string debugId = 1;</code>
             */
            public Builder clearDebugId() {
                copyOnWrite();
                instance.clearDebugId();
                return this;
            }

            /**
             * <code>optional string debugId = 1;</code>
             */
            public Builder setDebugIdBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setDebugIdBytes(value);
                return this;
            }

            /**
             * <code>optional string userId = 2;</code>
             */
            public String getUserId() {
                return instance.getUserId();
            }

            /**
             * <code>optional string userId = 2;</code>
             */
            public com.google.protobuf.ByteString
            getUserIdBytes() {
                return instance.getUserIdBytes();
            }

            /**
             * <code>optional string userId = 2;</code>
             */
            public Builder setUserId(
                    String value) {
                copyOnWrite();
                instance.setUserId(value);
                return this;
            }

            /**
             * <code>optional string userId = 2;</code>
             */
            public Builder clearUserId() {
                copyOnWrite();
                instance.clearUserId();
                return this;
            }

            /**
             * <code>optional string userId = 2;</code>
             */
            public Builder setUserIdBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setUserIdBytes(value);
                return this;
            }

            /**
             * <pre>
             * Can be user agent or device id
             * </pre>
             *
             * <code>optional string client = 3;</code>
             */
            public String getClient() {
                return instance.getClient();
            }

            /**
             * <pre>
             * Can be user agent or device id
             * </pre>
             *
             * <code>optional string client = 3;</code>
             */
            public com.google.protobuf.ByteString
            getClientBytes() {
                return instance.getClientBytes();
            }

            /**
             * <pre>
             * Can be user agent or device id
             * </pre>
             *
             * <code>optional string client = 3;</code>
             */
            public Builder setClient(
                    String value) {
                copyOnWrite();
                instance.setClient(value);
                return this;
            }

            /**
             * <pre>
             * Can be user agent or device id
             * </pre>
             *
             * <code>optional string client = 3;</code>
             */
            public Builder clearClient() {
                copyOnWrite();
                instance.clearClient();
                return this;
            }

            /**
             * <pre>
             * Can be user agent or device id
             * </pre>
             *
             * <code>optional string client = 3;</code>
             */
            public Builder setClientBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setClientBytes(value);
                return this;
            }

            /**
             * <code>optional string locale = 4;</code>
             */
            public String getLocale() {
                return instance.getLocale();
            }

            /**
             * <code>optional string locale = 4;</code>
             */
            public com.google.protobuf.ByteString
            getLocaleBytes() {
                return instance.getLocaleBytes();
            }

            /**
             * <code>optional string locale = 4;</code>
             */
            public Builder setLocale(
                    String value) {
                copyOnWrite();
                instance.setLocale(value);
                return this;
            }

            /**
             * <code>optional string locale = 4;</code>
             */
            public Builder clearLocale() {
                copyOnWrite();
                instance.clearLocale();
                return this;
            }

            /**
             * <code>optional string locale = 4;</code>
             */
            public Builder setLocaleBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setLocaleBytes(value);
                return this;
            }

            /**
             * <code>optional string traceId = 5;</code>
             */
            public String getTraceId() {
                return instance.getTraceId();
            }

            /**
             * <code>optional string traceId = 5;</code>
             */
            public com.google.protobuf.ByteString
            getTraceIdBytes() {
                return instance.getTraceIdBytes();
            }

            /**
             * <code>optional string traceId = 5;</code>
             */
            public Builder setTraceId(
                    String value) {
                copyOnWrite();
                instance.setTraceId(value);
                return this;
            }

            /**
             * <code>optional string traceId = 5;</code>
             */
            public Builder clearTraceId() {
                copyOnWrite();
                instance.clearTraceId();
                return this;
            }

            /**
             * <code>optional string traceId = 5;</code>
             */
            public Builder setTraceIdBytes(
                    com.google.protobuf.ByteString value) {
                copyOnWrite();
                instance.setTraceIdBytes(value);
                return this;
            }

            // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.Debug)
        }

        protected final Object dynamicMethod(
                MethodToInvoke method,
                Object arg0, Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new com.brilltech.jelp.entities.TreeleafProto.Debug();
                }
                case IS_INITIALIZED: {
                    return DEFAULT_INSTANCE;
                }
                case MAKE_IMMUTABLE: {
                    return null;
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case VISIT: {
                    Visitor visitor = (Visitor) arg0;
                    com.brilltech.jelp.entities.TreeleafProto.Debug other = (com.brilltech.jelp.entities.TreeleafProto.Debug) arg1;
                    debugId_ = visitor.visitString(!debugId_.isEmpty(), debugId_,
                            !other.debugId_.isEmpty(), other.debugId_);
                    userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
                            !other.userId_.isEmpty(), other.userId_);
                    client_ = visitor.visitString(!client_.isEmpty(), client_,
                            !other.client_.isEmpty(), other.client_);
                    locale_ = visitor.visitString(!locale_.isEmpty(), locale_,
                            !other.locale_.isEmpty(), other.locale_);
                    traceId_ = visitor.visitString(!traceId_.isEmpty(), traceId_,
                            !other.traceId_.isEmpty(), other.traceId_);
                    if (visitor == MergeFromVisitor
                            .INSTANCE) {
                    }
                    return this;
                }
                case MERGE_FROM_STREAM: {
                    com.google.protobuf.CodedInputStream input =
                            (com.google.protobuf.CodedInputStream) arg0;
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                            (com.google.protobuf.ExtensionRegistryLite) arg1;
                    try {
                        boolean done = false;
                        while (!done) {
                            int tag = input.readTag();
                            switch (tag) {
                                case 0:
                                    done = true;
                                    break;
                                default: {
                                    if (!input.skipField(tag)) {
                                        done = true;
                                    }
                                    break;
                                }
                                case 10: {
                                    String s = input.readStringRequireUtf8();

                                    debugId_ = s;
                                    break;
                                }
                                case 18: {
                                    String s = input.readStringRequireUtf8();

                                    userId_ = s;
                                    break;
                                }
                                case 26: {
                                    String s = input.readStringRequireUtf8();

                                    client_ = s;
                                    break;
                                }
                                case 34: {
                                    String s = input.readStringRequireUtf8();

                                    locale_ = s;
                                    break;
                                }
                                case 42: {
                                    String s = input.readStringRequireUtf8();

                                    traceId_ = s;
                                    break;
                                }
                            }
                        }
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw new RuntimeException(e.setUnfinishedMessage(this));
                    } catch (java.io.IOException e) {
                        throw new RuntimeException(
                                new com.google.protobuf.InvalidProtocolBufferException(
                                        e.getMessage()).setUnfinishedMessage(this));
                    } finally {
                    }
                }
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    if (PARSER == null) {
                        synchronized (com.brilltech.jelp.entities.TreeleafProto.Debug.class) {
                            if (PARSER == null) {
                                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                            }
                        }
                    }
                    return PARSER;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.Debug)
        private static final com.brilltech.jelp.entities.TreeleafProto.Debug DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Debug();
            DEFAULT_INSTANCE.makeImmutable();
        }

        public static com.brilltech.jelp.entities.TreeleafProto.Debug getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<Debug> PARSER;

        public static com.google.protobuf.Parser<Debug> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
