// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.brilltech.jelp.entities;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.User)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string userId = 1;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string emailPhone = 2;</code>
     */
    String getEmailPhone();
    /**
     * <code>optional string emailPhone = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailPhoneBytes();

    /**
     * <code>optional string fullName = 3;</code>
     */
    String getFullName();
    /**
     * <code>optional string fullName = 3;</code>
     */
    com.google.protobuf.ByteString
        getFullNameBytes();

    /**
     * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
     */
    int getGenderValue();
    /**
     * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
     */
    JelpProto.Gender getGender();

    /**
     * <code>optional string country = 5;</code>
     */
    String getCountry();
    /**
     * <code>optional string country = 5;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <code>optional bool agreeTermsConditions = 6;</code>
     */
    boolean getAgreeTermsConditions();

    /**
     * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
     */
    int getUserTypeValue();
    /**
     * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
     */
    JelpProto.UserType getUserType();

    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
     */
    int getUserStatusValue();
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
     */
    JelpProto.UserStatus getUserStatus();

    /**
     * <code>optional string profilePicUrl = 9;</code>
     */
    String getProfilePicUrl();
    /**
     * <code>optional string profilePicUrl = 9;</code>
     */
    com.google.protobuf.ByteString
        getProfilePicUrlBytes();

    /**
     * <code>optional bool isDeleted = 10;</code>
     */
    boolean getIsDeleted();

    /**
     * <code>optional int64 createdAt = 11;</code>
     */
    long getCreatedAt();

    /**
     * <code>optional int64 updatedAt = 12;</code>
     */
    long getUpdatedAt();

    /**
     * <code>optional string address = 13;</code>
     */
    String getAddress();
    /**
     * <code>optional string address = 13;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageLite<
          User, User.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.User)
      UserOrBuilder {
    private User() {
      userId_ = "";
      emailPhone_ = "";
      fullName_ = "";
      country_ = "";
      profilePicUrl_ = "";
      address_ = "";
    }
    public static final int USERID_FIELD_NUMBER = 1;
    private String userId_;
    /**
     * <code>optional string userId = 1;</code>
     */
    public String getUserId() {
      return userId_;
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    private void setUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    private void clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value.toStringUtf8();
    }

    public static final int EMAILPHONE_FIELD_NUMBER = 2;
    private String emailPhone_;
    /**
     * <code>optional string emailPhone = 2;</code>
     */
    public String getEmailPhone() {
      return emailPhone_;
    }
    /**
     * <code>optional string emailPhone = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailPhoneBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emailPhone_);
    }
    /**
     * <code>optional string emailPhone = 2;</code>
     */
    private void setEmailPhone(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emailPhone_ = value;
    }
    /**
     * <code>optional string emailPhone = 2;</code>
     */
    private void clearEmailPhone() {
      
      emailPhone_ = getDefaultInstance().getEmailPhone();
    }
    /**
     * <code>optional string emailPhone = 2;</code>
     */
    private void setEmailPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emailPhone_ = value.toStringUtf8();
    }

    public static final int FULLNAME_FIELD_NUMBER = 3;
    private String fullName_;
    /**
     * <code>optional string fullName = 3;</code>
     */
    public String getFullName() {
      return fullName_;
    }
    /**
     * <code>optional string fullName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fullName_);
    }
    /**
     * <code>optional string fullName = 3;</code>
     */
    private void setFullName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fullName_ = value;
    }
    /**
     * <code>optional string fullName = 3;</code>
     */
    private void clearFullName() {
      
      fullName_ = getDefaultInstance().getFullName();
    }
    /**
     * <code>optional string fullName = 3;</code>
     */
    private void setFullNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fullName_ = value.toStringUtf8();
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private int gender_;
    /**
     * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
     */
    public JelpProto.Gender getGender() {
      JelpProto.Gender result = JelpProto.Gender.forNumber(gender_);
      return result == null ? JelpProto.Gender.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
     */
    private void setGenderValue(int value) {
        gender_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
     */
    private void setGender(JelpProto.Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gender_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
     */
    private void clearGender() {
      
      gender_ = 0;
    }

    public static final int COUNTRY_FIELD_NUMBER = 5;
    private String country_;
    /**
     * <code>optional string country = 5;</code>
     */
    public String getCountry() {
      return country_;
    }
    /**
     * <code>optional string country = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(country_);
    }
    /**
     * <code>optional string country = 5;</code>
     */
    private void setCountry(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      country_ = value;
    }
    /**
     * <code>optional string country = 5;</code>
     */
    private void clearCountry() {
      
      country_ = getDefaultInstance().getCountry();
    }
    /**
     * <code>optional string country = 5;</code>
     */
    private void setCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      country_ = value.toStringUtf8();
    }

    public static final int AGREETERMSCONDITIONS_FIELD_NUMBER = 6;
    private boolean agreeTermsConditions_;
    /**
     * <code>optional bool agreeTermsConditions = 6;</code>
     */
    public boolean getAgreeTermsConditions() {
      return agreeTermsConditions_;
    }
    /**
     * <code>optional bool agreeTermsConditions = 6;</code>
     */
    private void setAgreeTermsConditions(boolean value) {
      
      agreeTermsConditions_ = value;
    }
    /**
     * <code>optional bool agreeTermsConditions = 6;</code>
     */
    private void clearAgreeTermsConditions() {
      
      agreeTermsConditions_ = false;
    }

    public static final int USERTYPE_FIELD_NUMBER = 7;
    private int userType_;
    /**
     * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
     */
    public int getUserTypeValue() {
      return userType_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
     */
    public JelpProto.UserType getUserType() {
      JelpProto.UserType result = JelpProto.UserType.forNumber(userType_);
      return result == null ? JelpProto.UserType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
     */
    private void setUserTypeValue(int value) {
        userType_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
     */
    private void setUserType(JelpProto.UserType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      userType_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
     */
    private void clearUserType() {
      
      userType_ = 0;
    }

    public static final int USERSTATUS_FIELD_NUMBER = 8;
    private int userStatus_;
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
     */
    public int getUserStatusValue() {
      return userStatus_;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
     */
    public JelpProto.UserStatus getUserStatus() {
      JelpProto.UserStatus result = JelpProto.UserStatus.forNumber(userStatus_);
      return result == null ? JelpProto.UserStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
     */
    private void setUserStatusValue(int value) {
        userStatus_ = value;
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
     */
    private void setUserStatus(JelpProto.UserStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      userStatus_ = value.getNumber();
    }
    /**
     * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
     */
    private void clearUserStatus() {
      
      userStatus_ = 0;
    }

    public static final int PROFILEPICURL_FIELD_NUMBER = 9;
    private String profilePicUrl_;
    /**
     * <code>optional string profilePicUrl = 9;</code>
     */
    public String getProfilePicUrl() {
      return profilePicUrl_;
    }
    /**
     * <code>optional string profilePicUrl = 9;</code>
     */
    public com.google.protobuf.ByteString
        getProfilePicUrlBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(profilePicUrl_);
    }
    /**
     * <code>optional string profilePicUrl = 9;</code>
     */
    private void setProfilePicUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      profilePicUrl_ = value;
    }
    /**
     * <code>optional string profilePicUrl = 9;</code>
     */
    private void clearProfilePicUrl() {
      
      profilePicUrl_ = getDefaultInstance().getProfilePicUrl();
    }
    /**
     * <code>optional string profilePicUrl = 9;</code>
     */
    private void setProfilePicUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      profilePicUrl_ = value.toStringUtf8();
    }

    public static final int ISDELETED_FIELD_NUMBER = 10;
    private boolean isDeleted_;
    /**
     * <code>optional bool isDeleted = 10;</code>
     */
    public boolean getIsDeleted() {
      return isDeleted_;
    }
    /**
     * <code>optional bool isDeleted = 10;</code>
     */
    private void setIsDeleted(boolean value) {
      
      isDeleted_ = value;
    }
    /**
     * <code>optional bool isDeleted = 10;</code>
     */
    private void clearIsDeleted() {
      
      isDeleted_ = false;
    }

    public static final int CREATEDAT_FIELD_NUMBER = 11;
    private long createdAt_;
    /**
     * <code>optional int64 createdAt = 11;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>optional int64 createdAt = 11;</code>
     */
    private void setCreatedAt(long value) {
      
      createdAt_ = value;
    }
    /**
     * <code>optional int64 createdAt = 11;</code>
     */
    private void clearCreatedAt() {
      
      createdAt_ = 0L;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 12;
    private long updatedAt_;
    /**
     * <code>optional int64 updatedAt = 12;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>optional int64 updatedAt = 12;</code>
     */
    private void setUpdatedAt(long value) {
      
      updatedAt_ = value;
    }
    /**
     * <code>optional int64 updatedAt = 12;</code>
     */
    private void clearUpdatedAt() {
      
      updatedAt_ = 0L;
    }

    public static final int ADDRESS_FIELD_NUMBER = 13;
    private String address_;
    /**
     * <code>optional string address = 13;</code>
     */
    public String getAddress() {
      return address_;
    }
    /**
     * <code>optional string address = 13;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(address_);
    }
    /**
     * <code>optional string address = 13;</code>
     */
    private void setAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
    }
    /**
     * <code>optional string address = 13;</code>
     */
    private void clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
    }
    /**
     * <code>optional string address = 13;</code>
     */
    private void setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!userId_.isEmpty()) {
        output.writeString(1, getUserId());
      }
      if (!emailPhone_.isEmpty()) {
        output.writeString(2, getEmailPhone());
      }
      if (!fullName_.isEmpty()) {
        output.writeString(3, getFullName());
      }
      if (gender_ != JelpProto.Gender.UNKNOWN_GENDER.getNumber()) {
        output.writeEnum(4, gender_);
      }
      if (!country_.isEmpty()) {
        output.writeString(5, getCountry());
      }
      if (agreeTermsConditions_ != false) {
        output.writeBool(6, agreeTermsConditions_);
      }
      if (userType_ != JelpProto.UserType.UNKNOWN_USER_TYPE.getNumber()) {
        output.writeEnum(7, userType_);
      }
      if (userStatus_ != JelpProto.UserStatus.UNKNOWN_USER_STATUS.getNumber()) {
        output.writeEnum(8, userStatus_);
      }
      if (!profilePicUrl_.isEmpty()) {
        output.writeString(9, getProfilePicUrl());
      }
      if (isDeleted_ != false) {
        output.writeBool(10, isDeleted_);
      }
      if (createdAt_ != 0L) {
        output.writeInt64(11, createdAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(12, updatedAt_);
      }
      if (!address_.isEmpty()) {
        output.writeString(13, getAddress());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!userId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUserId());
      }
      if (!emailPhone_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEmailPhone());
      }
      if (!fullName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getFullName());
      }
      if (gender_ != JelpProto.Gender.UNKNOWN_GENDER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, gender_);
      }
      if (!country_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getCountry());
      }
      if (agreeTermsConditions_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, agreeTermsConditions_);
      }
      if (userType_ != JelpProto.UserType.UNKNOWN_USER_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, userType_);
      }
      if (userStatus_ != JelpProto.UserStatus.UNKNOWN_USER_STATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, userStatus_);
      }
      if (!profilePicUrl_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getProfilePicUrl());
      }
      if (isDeleted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, isDeleted_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, createdAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, updatedAt_);
      }
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(13, getAddress());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          User, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.User)
        UserOrBuilder {
      // Construct using com.brilltech.jelp.entities.UserProto.User.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string userId = 1;</code>
       */
      public String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      /**
       * <code>optional string emailPhone = 2;</code>
       */
      public String getEmailPhone() {
        return instance.getEmailPhone();
      }
      /**
       * <code>optional string emailPhone = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailPhoneBytes() {
        return instance.getEmailPhoneBytes();
      }
      /**
       * <code>optional string emailPhone = 2;</code>
       */
      public Builder setEmailPhone(
          String value) {
        copyOnWrite();
        instance.setEmailPhone(value);
        return this;
      }
      /**
       * <code>optional string emailPhone = 2;</code>
       */
      public Builder clearEmailPhone() {
        copyOnWrite();
        instance.clearEmailPhone();
        return this;
      }
      /**
       * <code>optional string emailPhone = 2;</code>
       */
      public Builder setEmailPhoneBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailPhoneBytes(value);
        return this;
      }

      /**
       * <code>optional string fullName = 3;</code>
       */
      public String getFullName() {
        return instance.getFullName();
      }
      /**
       * <code>optional string fullName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        return instance.getFullNameBytes();
      }
      /**
       * <code>optional string fullName = 3;</code>
       */
      public Builder setFullName(
          String value) {
        copyOnWrite();
        instance.setFullName(value);
        return this;
      }
      /**
       * <code>optional string fullName = 3;</code>
       */
      public Builder clearFullName() {
        copyOnWrite();
        instance.clearFullName();
        return this;
      }
      /**
       * <code>optional string fullName = 3;</code>
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFullNameBytes(value);
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
       */
      public int getGenderValue() {
        return instance.getGenderValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
       */
      public Builder setGenderValue(int value) {
        copyOnWrite();
        instance.setGenderValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
       */
      public JelpProto.Gender getGender() {
        return instance.getGender();
      }
      /**
       * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
       */
      public Builder setGender(JelpProto.Gender value) {
        copyOnWrite();
        instance.setGender(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.Gender gender = 4;</code>
       */
      public Builder clearGender() {
        copyOnWrite();
        instance.clearGender();
        return this;
      }

      /**
       * <code>optional string country = 5;</code>
       */
      public String getCountry() {
        return instance.getCountry();
      }
      /**
       * <code>optional string country = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        return instance.getCountryBytes();
      }
      /**
       * <code>optional string country = 5;</code>
       */
      public Builder setCountry(
          String value) {
        copyOnWrite();
        instance.setCountry(value);
        return this;
      }
      /**
       * <code>optional string country = 5;</code>
       */
      public Builder clearCountry() {
        copyOnWrite();
        instance.clearCountry();
        return this;
      }
      /**
       * <code>optional string country = 5;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCountryBytes(value);
        return this;
      }

      /**
       * <code>optional bool agreeTermsConditions = 6;</code>
       */
      public boolean getAgreeTermsConditions() {
        return instance.getAgreeTermsConditions();
      }
      /**
       * <code>optional bool agreeTermsConditions = 6;</code>
       */
      public Builder setAgreeTermsConditions(boolean value) {
        copyOnWrite();
        instance.setAgreeTermsConditions(value);
        return this;
      }
      /**
       * <code>optional bool agreeTermsConditions = 6;</code>
       */
      public Builder clearAgreeTermsConditions() {
        copyOnWrite();
        instance.clearAgreeTermsConditions();
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
       */
      public int getUserTypeValue() {
        return instance.getUserTypeValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
       */
      public Builder setUserTypeValue(int value) {
        copyOnWrite();
        instance.setUserTypeValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
       */
      public JelpProto.UserType getUserType() {
        return instance.getUserType();
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
       */
      public Builder setUserType(JelpProto.UserType value) {
        copyOnWrite();
        instance.setUserType(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserType userType = 7;</code>
       */
      public Builder clearUserType() {
        copyOnWrite();
        instance.clearUserType();
        return this;
      }

      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
       */
      public int getUserStatusValue() {
        return instance.getUserStatusValue();
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
       */
      public Builder setUserStatusValue(int value) {
        copyOnWrite();
        instance.setUserStatusValue(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
       */
      public JelpProto.UserStatus getUserStatus() {
        return instance.getUserStatus();
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
       */
      public Builder setUserStatus(JelpProto.UserStatus value) {
        copyOnWrite();
        instance.setUserStatus(value);
        return this;
      }
      /**
       * <code>optional .brilltech.jelp.entities.UserStatus userStatus = 8;</code>
       */
      public Builder clearUserStatus() {
        copyOnWrite();
        instance.clearUserStatus();
        return this;
      }

      /**
       * <code>optional string profilePicUrl = 9;</code>
       */
      public String getProfilePicUrl() {
        return instance.getProfilePicUrl();
      }
      /**
       * <code>optional string profilePicUrl = 9;</code>
       */
      public com.google.protobuf.ByteString
          getProfilePicUrlBytes() {
        return instance.getProfilePicUrlBytes();
      }
      /**
       * <code>optional string profilePicUrl = 9;</code>
       */
      public Builder setProfilePicUrl(
          String value) {
        copyOnWrite();
        instance.setProfilePicUrl(value);
        return this;
      }
      /**
       * <code>optional string profilePicUrl = 9;</code>
       */
      public Builder clearProfilePicUrl() {
        copyOnWrite();
        instance.clearProfilePicUrl();
        return this;
      }
      /**
       * <code>optional string profilePicUrl = 9;</code>
       */
      public Builder setProfilePicUrlBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProfilePicUrlBytes(value);
        return this;
      }

      /**
       * <code>optional bool isDeleted = 10;</code>
       */
      public boolean getIsDeleted() {
        return instance.getIsDeleted();
      }
      /**
       * <code>optional bool isDeleted = 10;</code>
       */
      public Builder setIsDeleted(boolean value) {
        copyOnWrite();
        instance.setIsDeleted(value);
        return this;
      }
      /**
       * <code>optional bool isDeleted = 10;</code>
       */
      public Builder clearIsDeleted() {
        copyOnWrite();
        instance.clearIsDeleted();
        return this;
      }

      /**
       * <code>optional int64 createdAt = 11;</code>
       */
      public long getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>optional int64 createdAt = 11;</code>
       */
      public Builder setCreatedAt(long value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 createdAt = 11;</code>
       */
      public Builder clearCreatedAt() {
        copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>optional int64 updatedAt = 12;</code>
       */
      public long getUpdatedAt() {
        return instance.getUpdatedAt();
      }
      /**
       * <code>optional int64 updatedAt = 12;</code>
       */
      public Builder setUpdatedAt(long value) {
        copyOnWrite();
        instance.setUpdatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 updatedAt = 12;</code>
       */
      public Builder clearUpdatedAt() {
        copyOnWrite();
        instance.clearUpdatedAt();
        return this;
      }

      /**
       * <code>optional string address = 13;</code>
       */
      public String getAddress() {
        return instance.getAddress();
      }
      /**
       * <code>optional string address = 13;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        return instance.getAddressBytes();
      }
      /**
       * <code>optional string address = 13;</code>
       */
      public Builder setAddress(
          String value) {
        copyOnWrite();
        instance.setAddress(value);
        return this;
      }
      /**
       * <code>optional string address = 13;</code>
       */
      public Builder clearAddress() {
        copyOnWrite();
        instance.clearAddress();
        return this;
      }
      /**
       * <code>optional string address = 13;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAddressBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.User)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new User();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          User other = (User) arg1;
          userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
              !other.userId_.isEmpty(), other.userId_);
          emailPhone_ = visitor.visitString(!emailPhone_.isEmpty(), emailPhone_,
              !other.emailPhone_.isEmpty(), other.emailPhone_);
          fullName_ = visitor.visitString(!fullName_.isEmpty(), fullName_,
              !other.fullName_.isEmpty(), other.fullName_);
          gender_ = visitor.visitInt(gender_ != 0, gender_,    other.gender_ != 0, other.gender_);
          country_ = visitor.visitString(!country_.isEmpty(), country_,
              !other.country_.isEmpty(), other.country_);
          agreeTermsConditions_ = visitor.visitBoolean(agreeTermsConditions_ != false, agreeTermsConditions_,
              other.agreeTermsConditions_ != false, other.agreeTermsConditions_);
          userType_ = visitor.visitInt(userType_ != 0, userType_,    other.userType_ != 0, other.userType_);
          userStatus_ = visitor.visitInt(userStatus_ != 0, userStatus_,    other.userStatus_ != 0, other.userStatus_);
          profilePicUrl_ = visitor.visitString(!profilePicUrl_.isEmpty(), profilePicUrl_,
              !other.profilePicUrl_.isEmpty(), other.profilePicUrl_);
          isDeleted_ = visitor.visitBoolean(isDeleted_ != false, isDeleted_,
              other.isDeleted_ != false, other.isDeleted_);
          createdAt_ = visitor.visitLong(createdAt_ != 0L, createdAt_,
              other.createdAt_ != 0L, other.createdAt_);
          updatedAt_ = visitor.visitLong(updatedAt_ != 0L, updatedAt_,
              other.updatedAt_ != 0L, other.updatedAt_);
          address_ = visitor.visitString(!address_.isEmpty(), address_,
              !other.address_.isEmpty(), other.address_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  userId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  emailPhone_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  fullName_ = s;
                  break;
                }
                case 32: {
                  int rawValue = input.readEnum();

                  gender_ = rawValue;
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  country_ = s;
                  break;
                }
                case 48: {

                  agreeTermsConditions_ = input.readBool();
                  break;
                }
                case 56: {
                  int rawValue = input.readEnum();

                  userType_ = rawValue;
                  break;
                }
                case 64: {
                  int rawValue = input.readEnum();

                  userStatus_ = rawValue;
                  break;
                }
                case 74: {
                  String s = input.readStringRequireUtf8();

                  profilePicUrl_ = s;
                  break;
                }
                case 80: {

                  isDeleted_ = input.readBool();
                  break;
                }
                case 88: {

                  createdAt_ = input.readInt64();
                  break;
                }
                case 96: {

                  updatedAt_ = input.readInt64();
                  break;
                }
                case 106: {
                  String s = input.readStringRequireUtf8();

                  address_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (User.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.User)
    private static final User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new User();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<User> PARSER;

    public static com.google.protobuf.Parser<User> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MedicalProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:brilltech.jelp.entities.MedicalProfile)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string medicalProfileId = 1;</code>
     */
    String getMedicalProfileId();
    /**
     * <code>optional string medicalProfileId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMedicalProfileIdBytes();

    /**
     * <code>optional string userId = 2;</code>
     */
    String getUserId();
    /**
     * <code>optional string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string details = 3;</code>
     */
    String getDetails();
    /**
     * <code>optional string details = 3;</code>
     */
    com.google.protobuf.ByteString
        getDetailsBytes();

    /**
     * <code>optional string medicareNumber = 4;</code>
     */
    String getMedicareNumber();
    /**
     * <code>optional string medicareNumber = 4;</code>
     */
    com.google.protobuf.ByteString
        getMedicareNumberBytes();

    /**
     * <code>optional bool isDeleted = 5;</code>
     */
    boolean getIsDeleted();

    /**
     * <code>optional int64 createdAt = 6;</code>
     */
    long getCreatedAt();

    /**
     * <code>optional int64 updatedAt = 7;</code>
     */
    long getUpdatedAt();
  }
  /**
   * Protobuf type {@code brilltech.jelp.entities.MedicalProfile}
   */
  public  static final class MedicalProfile extends
      com.google.protobuf.GeneratedMessageLite<
          MedicalProfile, MedicalProfile.Builder> implements
      // @@protoc_insertion_point(message_implements:brilltech.jelp.entities.MedicalProfile)
      MedicalProfileOrBuilder {
    private MedicalProfile() {
      medicalProfileId_ = "";
      userId_ = "";
      details_ = "";
      medicareNumber_ = "";
    }
    public static final int MEDICALPROFILEID_FIELD_NUMBER = 1;
    private String medicalProfileId_;
    /**
     * <code>optional string medicalProfileId = 1;</code>
     */
    public String getMedicalProfileId() {
      return medicalProfileId_;
    }
    /**
     * <code>optional string medicalProfileId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMedicalProfileIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(medicalProfileId_);
    }
    /**
     * <code>optional string medicalProfileId = 1;</code>
     */
    private void setMedicalProfileId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      medicalProfileId_ = value;
    }
    /**
     * <code>optional string medicalProfileId = 1;</code>
     */
    private void clearMedicalProfileId() {
      
      medicalProfileId_ = getDefaultInstance().getMedicalProfileId();
    }
    /**
     * <code>optional string medicalProfileId = 1;</code>
     */
    private void setMedicalProfileIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      medicalProfileId_ = value.toStringUtf8();
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private String userId_;
    /**
     * <code>optional string userId = 2;</code>
     */
    public String getUserId() {
      return userId_;
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    private void setUserId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    private void clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>optional string userId = 2;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value.toStringUtf8();
    }

    public static final int DETAILS_FIELD_NUMBER = 3;
    private String details_;
    /**
     * <code>optional string details = 3;</code>
     */
    public String getDetails() {
      return details_;
    }
    /**
     * <code>optional string details = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDetailsBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(details_);
    }
    /**
     * <code>optional string details = 3;</code>
     */
    private void setDetails(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      details_ = value;
    }
    /**
     * <code>optional string details = 3;</code>
     */
    private void clearDetails() {
      
      details_ = getDefaultInstance().getDetails();
    }
    /**
     * <code>optional string details = 3;</code>
     */
    private void setDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      details_ = value.toStringUtf8();
    }

    public static final int MEDICARENUMBER_FIELD_NUMBER = 4;
    private String medicareNumber_;
    /**
     * <code>optional string medicareNumber = 4;</code>
     */
    public String getMedicareNumber() {
      return medicareNumber_;
    }
    /**
     * <code>optional string medicareNumber = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMedicareNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(medicareNumber_);
    }
    /**
     * <code>optional string medicareNumber = 4;</code>
     */
    private void setMedicareNumber(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      medicareNumber_ = value;
    }
    /**
     * <code>optional string medicareNumber = 4;</code>
     */
    private void clearMedicareNumber() {
      
      medicareNumber_ = getDefaultInstance().getMedicareNumber();
    }
    /**
     * <code>optional string medicareNumber = 4;</code>
     */
    private void setMedicareNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      medicareNumber_ = value.toStringUtf8();
    }

    public static final int ISDELETED_FIELD_NUMBER = 5;
    private boolean isDeleted_;
    /**
     * <code>optional bool isDeleted = 5;</code>
     */
    public boolean getIsDeleted() {
      return isDeleted_;
    }
    /**
     * <code>optional bool isDeleted = 5;</code>
     */
    private void setIsDeleted(boolean value) {
      
      isDeleted_ = value;
    }
    /**
     * <code>optional bool isDeleted = 5;</code>
     */
    private void clearIsDeleted() {
      
      isDeleted_ = false;
    }

    public static final int CREATEDAT_FIELD_NUMBER = 6;
    private long createdAt_;
    /**
     * <code>optional int64 createdAt = 6;</code>
     */
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>optional int64 createdAt = 6;</code>
     */
    private void setCreatedAt(long value) {
      
      createdAt_ = value;
    }
    /**
     * <code>optional int64 createdAt = 6;</code>
     */
    private void clearCreatedAt() {
      
      createdAt_ = 0L;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 7;
    private long updatedAt_;
    /**
     * <code>optional int64 updatedAt = 7;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }
    /**
     * <code>optional int64 updatedAt = 7;</code>
     */
    private void setUpdatedAt(long value) {
      
      updatedAt_ = value;
    }
    /**
     * <code>optional int64 updatedAt = 7;</code>
     */
    private void clearUpdatedAt() {
      
      updatedAt_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!medicalProfileId_.isEmpty()) {
        output.writeString(1, getMedicalProfileId());
      }
      if (!userId_.isEmpty()) {
        output.writeString(2, getUserId());
      }
      if (!details_.isEmpty()) {
        output.writeString(3, getDetails());
      }
      if (!medicareNumber_.isEmpty()) {
        output.writeString(4, getMedicareNumber());
      }
      if (isDeleted_ != false) {
        output.writeBool(5, isDeleted_);
      }
      if (createdAt_ != 0L) {
        output.writeInt64(6, createdAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(7, updatedAt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!medicalProfileId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMedicalProfileId());
      }
      if (!userId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getUserId());
      }
      if (!details_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getDetails());
      }
      if (!medicareNumber_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getMedicareNumber());
      }
      if (isDeleted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isDeleted_);
      }
      if (createdAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createdAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, updatedAt_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static MedicalProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MedicalProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MedicalProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MedicalProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MedicalProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static MedicalProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static MedicalProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static MedicalProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static MedicalProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static MedicalProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MedicalProfile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code brilltech.jelp.entities.MedicalProfile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          MedicalProfile, Builder> implements
        // @@protoc_insertion_point(builder_implements:brilltech.jelp.entities.MedicalProfile)
        MedicalProfileOrBuilder {
      // Construct using com.brilltech.jelp.entities.UserProto.MedicalProfile.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string medicalProfileId = 1;</code>
       */
      public String getMedicalProfileId() {
        return instance.getMedicalProfileId();
      }
      /**
       * <code>optional string medicalProfileId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMedicalProfileIdBytes() {
        return instance.getMedicalProfileIdBytes();
      }
      /**
       * <code>optional string medicalProfileId = 1;</code>
       */
      public Builder setMedicalProfileId(
          String value) {
        copyOnWrite();
        instance.setMedicalProfileId(value);
        return this;
      }
      /**
       * <code>optional string medicalProfileId = 1;</code>
       */
      public Builder clearMedicalProfileId() {
        copyOnWrite();
        instance.clearMedicalProfileId();
        return this;
      }
      /**
       * <code>optional string medicalProfileId = 1;</code>
       */
      public Builder setMedicalProfileIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMedicalProfileIdBytes(value);
        return this;
      }

      /**
       * <code>optional string userId = 2;</code>
       */
      public String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserId(
          String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>optional string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      /**
       * <code>optional string details = 3;</code>
       */
      public String getDetails() {
        return instance.getDetails();
      }
      /**
       * <code>optional string details = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDetailsBytes() {
        return instance.getDetailsBytes();
      }
      /**
       * <code>optional string details = 3;</code>
       */
      public Builder setDetails(
          String value) {
        copyOnWrite();
        instance.setDetails(value);
        return this;
      }
      /**
       * <code>optional string details = 3;</code>
       */
      public Builder clearDetails() {
        copyOnWrite();
        instance.clearDetails();
        return this;
      }
      /**
       * <code>optional string details = 3;</code>
       */
      public Builder setDetailsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDetailsBytes(value);
        return this;
      }

      /**
       * <code>optional string medicareNumber = 4;</code>
       */
      public String getMedicareNumber() {
        return instance.getMedicareNumber();
      }
      /**
       * <code>optional string medicareNumber = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMedicareNumberBytes() {
        return instance.getMedicareNumberBytes();
      }
      /**
       * <code>optional string medicareNumber = 4;</code>
       */
      public Builder setMedicareNumber(
          String value) {
        copyOnWrite();
        instance.setMedicareNumber(value);
        return this;
      }
      /**
       * <code>optional string medicareNumber = 4;</code>
       */
      public Builder clearMedicareNumber() {
        copyOnWrite();
        instance.clearMedicareNumber();
        return this;
      }
      /**
       * <code>optional string medicareNumber = 4;</code>
       */
      public Builder setMedicareNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMedicareNumberBytes(value);
        return this;
      }

      /**
       * <code>optional bool isDeleted = 5;</code>
       */
      public boolean getIsDeleted() {
        return instance.getIsDeleted();
      }
      /**
       * <code>optional bool isDeleted = 5;</code>
       */
      public Builder setIsDeleted(boolean value) {
        copyOnWrite();
        instance.setIsDeleted(value);
        return this;
      }
      /**
       * <code>optional bool isDeleted = 5;</code>
       */
      public Builder clearIsDeleted() {
        copyOnWrite();
        instance.clearIsDeleted();
        return this;
      }

      /**
       * <code>optional int64 createdAt = 6;</code>
       */
      public long getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>optional int64 createdAt = 6;</code>
       */
      public Builder setCreatedAt(long value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 createdAt = 6;</code>
       */
      public Builder clearCreatedAt() {
        copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>optional int64 updatedAt = 7;</code>
       */
      public long getUpdatedAt() {
        return instance.getUpdatedAt();
      }
      /**
       * <code>optional int64 updatedAt = 7;</code>
       */
      public Builder setUpdatedAt(long value) {
        copyOnWrite();
        instance.setUpdatedAt(value);
        return this;
      }
      /**
       * <code>optional int64 updatedAt = 7;</code>
       */
      public Builder clearUpdatedAt() {
        copyOnWrite();
        instance.clearUpdatedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:brilltech.jelp.entities.MedicalProfile)
    }
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new MedicalProfile();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          MedicalProfile other = (MedicalProfile) arg1;
          medicalProfileId_ = visitor.visitString(!medicalProfileId_.isEmpty(), medicalProfileId_,
              !other.medicalProfileId_.isEmpty(), other.medicalProfileId_);
          userId_ = visitor.visitString(!userId_.isEmpty(), userId_,
              !other.userId_.isEmpty(), other.userId_);
          details_ = visitor.visitString(!details_.isEmpty(), details_,
              !other.details_.isEmpty(), other.details_);
          medicareNumber_ = visitor.visitString(!medicareNumber_.isEmpty(), medicareNumber_,
              !other.medicareNumber_.isEmpty(), other.medicareNumber_);
          isDeleted_ = visitor.visitBoolean(isDeleted_ != false, isDeleted_,
              other.isDeleted_ != false, other.isDeleted_);
          createdAt_ = visitor.visitLong(createdAt_ != 0L, createdAt_,
              other.createdAt_ != 0L, other.createdAt_);
          updatedAt_ = visitor.visitLong(updatedAt_ != 0L, updatedAt_,
              other.updatedAt_ != 0L, other.updatedAt_);
          if (visitor == MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  medicalProfileId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  userId_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  details_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  medicareNumber_ = s;
                  break;
                }
                case 40: {

                  isDeleted_ = input.readBool();
                  break;
                }
                case 48: {

                  createdAt_ = input.readInt64();
                  break;
                }
                case 56: {

                  updatedAt_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (MedicalProfile.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:brilltech.jelp.entities.MedicalProfile)
    private static final MedicalProfile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MedicalProfile();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static MedicalProfile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MedicalProfile> PARSER;

    public static com.google.protobuf.Parser<MedicalProfile> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
